In [1]:
import pandas as pd

In [115]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별인구수.csv", encoding="cp949")
df

,행정구역,2024년09월_계_총인구수,2024년09월_계_연령구간인구수,2024년09월_계_0~9세,2024년09월_남_총인구수,2024년09월_남_연령구간인구수,2024년09월_남_0~9세,2024년09월_여_총인구수,2024년09월_여_연령구간인구수,2024년09월_여_0~9세
0,서울특별시 (1100000000),"9,350,995","489,540","489,540","4,515,791","250,909","250,909","4,835,204","238,631","238,631"
1,서울특별시 종로구 (1111000000),"138,879","5,614","5,614","66,846","2,855","2,855","72,033","2,759","2,759"
2,서울특별시 중구 (1114000000),"121,324","5,380","5,380","58,447","2,737","2,737","62,877","2,643","2,643"
3,서울특별시 용산구 (1117000000),"205,145","10,377","10,377","98,118","5,256","5,256","107,027","5,121","5,121"
4,서울특별시 성동구 (1120000000),"275,403","16,200","16,200","133,271","8,376","8,376","142,132","7,824","7,824"
...,...,...,...,...,...,...,...,...,...,...
289,경상남도 거창군 (4888000000),"59,737","2,835","2,835","29,396","1,465","1,465","30,341","1,370","1,370"
290,경상남도 합천군 (4889000000),"40,440","1,061","1,061","19,860",564,564,"20,580",497,497
291,제주특별자치도 (5000000000),"671,064","48,496","48,496","335,717","24,851","24,851","335,347","23,645","23,645"
292,제주특별자치도 제주시 (5011000000),"488,844","36,408","36,408","244,006","18,585","18,585","244,838","17,823","17,823"
293,제주특별자치도 서귀포시 (5013000000),"182,220","12,088","12,088","91,711","6,266","6,266","90,509","5,822","5,822"

In [116]:
df_pop = df[["행정구역", "2024년09월_계_총인구수"]]
df_pop

                          행정구역 2024년09월_계_총인구수
0          서울특별시  (1100000000)       9,350,995
1       서울특별시 종로구 (1111000000)         138,879
2        서울특별시 중구 (1114000000)         121,324
3       서울특별시 용산구 (1117000000)         205,145
4       서울특별시 성동구 (1120000000)         275,403
..                         ...             ...
289      경상남도 거창군 (4888000000)          59,737
290      경상남도 합천군 (4889000000)          40,440
291      제주특별자치도  (5000000000)         671,064
292   제주특별자치도 제주시 (5011000000)         488,844
293  제주특별자치도 서귀포시 (5013000000)         182,220

[294 rows x 2 columns]

In [205]:
## 인구 데이터 중 "0" 인 것들 삭제
df_pop = df_pop[df_pop["2024년09월_계_총인구수"] != "0"]
df_pop

                    시군구코드명 2024년09월_계_총인구수   0
0                       서울       9,350,995  서울
1                      종로구         138,879  서울
2                       중구         121,324  서울
3                      용산구         205,145  서울
4                      성동구         275,403  서울
..                     ...             ...  ..
276                    거창군          59,737  서울
277                    합천군          40,440  서울
278  제주특별자치도  (5000000000)         671,064  서울
279                    제주시         488,844  서울
280                   서귀포시         182,220  서울

[281 rows x 3 columns]

In [134]:
## 병원 데이터 받아오기
df_hos = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/2024의원통합데이터.csv")
df_hos.columns

Index(['Unnamed: 0', '암호화요양기호', '요양기관명', '종별코드명', '설립구분코드명', '시도코드명', '시군구코드명',
       '개설일자', '성인중환자병상수', '일반입원실병상수', '소아중환자병상수', '신생아중환자병상수', '분만실병상수',
       '수술실병상수', '응급실병상수', '물리치료실병상수', '정신과폐쇄상급병상수', '정신과폐쇄일반병상수',
       '정신과개방상급병상수', '정신과폐쇄개방병상수', '격리병실병상수', '무균치료실병상수', '총의사수', '의과일반의 인원수',
       '의과인턴 인원수', '의과레지던트 인원수', '의과전문의 인원수', '치과일반의 인원수', '치과인턴 인원수',
       '치과레지던트 인원수', '치과전문의 인원수', '한방일반의 인원수', '한방인턴 인원수', '한방레지던트 인원수',
       '한방전문의 인원수', '조산사 인원수', '진료과목코드명', '과목별 전문의수'],
      dtype='object')

In [207]:
df_pop

                    시군구코드명 2024년09월_계_총인구수   0
0                       서울       9,350,995  서울
1                      종로구         138,879  서울
2                       중구         121,324  서울
3                      용산구         205,145  서울
4                      성동구         275,403  서울
..                     ...             ...  ..
276                    거창군          59,737  서울
277                    합천군          40,440  서울
278  제주특별자치도  (5000000000)         671,064  서울
279                    제주시         488,844  서울
280                   서귀포시         182,220  서울

[281 rows x 3 columns]

In [206]:
## 칼럼명 '시군구도시명'으로 통일
df_pop.rename(columns={'행정구역': '시군구코드명'}, inplace=True)

In [219]:
## 인덱스 재정렬
df_pop.reset_index(drop=True, inplace=True)

In [127]:
original_list = df_hos["시군구코드명"].unique()
original_list

array(['대구중구', '구리시', '성남수정구', '고양덕양구', '대전중구', '부산금정구', '부천원미구', '대전유성구',
       '부산동래구', '파주시', '부천소사구', '세종시', '광주시', '천안서북구', '금천구', '서초구',
       '시흥시', '전주완산구', '광진구', '거제시', '영주시', '강남구', '마포구', '도봉구', '성동구',
       '양주시', '부산서구', '광주광산구', '울산중구', '부산동구', '화성시', '군포시', '보령시',
       '고양일산서구', '고양일산동구', '인천서구', '평택시', '칠곡군', '동대문구', '대구수성구', '부산남구',
       '안산단원구', '안산상록구', '인천미추홀구', '창원마산회원구', '울산남구', '송파구', '성남분당구',
       '부산해운대구', '동작구', '용인기흥구', '광주북구', '은평구', '대구달서구', '인천중구', '대구북구',
       '용인수지구', '용인처인구', '김포시', '안양동안구', '부산진구', '양산시', '광주서구', '옥천군',
       '용산구', '남양주시', '창원진해구', '부산수영구', '제주시', '김해시', '수원권선구', '대전대덕구',
       '중랑구', '충주시', '수원영통구', '대구달성군', '철원군', '인천남동구', '노원구', '대구남구',
       '산청군', '관악구', '광주남구', '수원팔달구', '안양만안구', '포항북구', '대전서구', '강동구',
       '음성군', '여수시', '강서구', '완주군', '경주시', '의성군', '고흥군', '광명시', '하남시',
       '익산시', '영등포구', '서대문구', '동해시', '수원장안구', '청주상당구', '구로구', '춘천시',
       '포항남구', '인천부평구', '성북구', '양천구', '인천계양구', '함양군', '창원성산구', '강북구',
       '당진시', '중구', '서산시', '종로구', '부산연제구', '부산사하구', '해남군', '진주시', '청주서원구',
       '천안동남구', '순천시', '오산시', '의왕시', '부산강서구', '인천연수구', '부산사상구', '김제시',
       '군산시', '정읍시', '순창군', '남원시', '장수군', '진안군', '전주덕진구', '홍성군', '의정부시',
       '경산시', '부산중구', '강릉시', '삼척시', '대구동구', '여주시', '울산북구', '창원의창구', '원주시',
       '남해군', '울산울주군', '고성군', '영천시', '창원마산합포구', '임실군', '부산북구', '부산영도구',
       '강진군', '서귀포시', '부산기장군', '구미시', '양평군', '안성시', '이천시', '가평군', '포천시',
       '부천오정구', '과천시', '고창군', '인천동구', '연천군', '거창군', '성남중원구', '동두천시',
       '인천옹진군', '부안군', '문경시', '논산시', '울진군', '대전동구', '제천시', '나주시', '무안군',
       '함안군', '예산군', '청주흥덕구', '진천군', '청주청원구', '괴산군', '단양군', '금산군', '청양군',
       '태안군', '아산시', '부여군', '서천군', '홍천군', '화천군', '울릉군', '대구서구', '공주시',
       '무주군', '계룡시', '목포시', '광주동구', '담양군', '신안군', '보성군', '곡성군', '광양시',
       '구례군', '장흥군', '안동시', '영광군', '진도군', '함평군', '완도군', '화순군', '장성군',
       '영암군', '창녕군', '영덕군', '상주시', '김천시', '성주군', '인천강화군', '영동군', '태백시',
       '속초시', '양구군', '보은군', '증평군', '대구군위군', '청송군', '횡성군', '인제군', '영월군',
       '예천군', '청도군', '고령군', '영양군', '봉화군', '밀양시', '의령군', '평창군', '울산동구',
       '하동군', '사천시', '정선군', '합천군', '양양군', '통영시'], dtype=object)

In [213]:
final_list = df_pop["시군구코드명"].unique()
final_list

array(['서울', '종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구',
       '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구',
       '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구',
       '부산광역시  (2600000000)', '부산광역시 중구 (2611000000)',
       '부산광역시 서구 (2614000000)', '부산광역시 동구 (2617000000)',
       '부산광역시 영도구 (2620000000)', '부산진구', '부산광역시 동래구 (2626000000)',
       '부산광역시 남구 (2629000000)', '부산광역시 북구 (2632000000)',
       '부산광역시 해운대구 (2635000000)', '부산광역시 사하구 (2638000000)',
       '부산광역시 금정구 (2641000000)', '부산광역시 강서구 (2644000000)',
       '부산광역시 연제구 (2647000000)', '부산광역시 수영구 (2650000000)',
       '부산광역시 사상구 (2653000000)', '부산광역시 기장군 (2671000000)',
       '대구광역시  (2700000000)', '대구광역시 중구 (2711000000)',
       '대구광역시 동구 (2714000000)', '대구광역시 서구 (2717000000)',
       '대구광역시 남구 (2720000000)', '대구광역시 북구 (2723000000)',
       '대구광역시 수성구 (2726000000)', '대구광역시 달서구 (2729000000)',
       '대구광역시 달성군 (2771000000)', '대구광역시 군위군 (2772000000)',
       '인천광역시  (2800000000)', '인천광역시 중구 (2811000000)',
       '인천광역시 동구 (2814000000)', '인천광역시 미추홀구 (2817700000)',
       '인천광역시 연수구 (2818500000)', '인천광역시 남동구 (2820000000)',
       '인천광역시 부평구 (2823700000)', '인천광역시 계양구 (2824500000)',
       '인천광역시 서구 (2826000000)', '인천광역시 강화군 (2871000000)',
       '인천광역시 옹진군 (2872000000)', '광주광역시  (2900000000)',
       '광주광역시 동구 (2911000000)', '광주광역시 서구 (2914000000)',
       '광주광역시 남구 (2915500000)', '광주광역시 북구 (2917000000)',
       '광주광역시 광산구 (2920000000)', '대전광역시  (3000000000)',
       '대전광역시 동구 (3011000000)', '대전광역시 중구 (3014000000)',
       '대전광역시 서구 (3017000000)', '대전광역시 유성구 (3020000000)',
       '대전광역시 대덕구 (3023000000)', '울산광역시  (3100000000)',
       '울산광역시 중구 (3111000000)', '울산광역시 남구 (3114000000)',
       '울산광역시 동구 (3117000000)', '울산광역시 북구 (3120000000)',
       '울산광역시 울주군 (3171000000)', '세종특별자치시  (3600000000)',
       '세종특별자치시  (3611000000)', '경기도  (4100000000)',
       '경기도 수원시 (4111000000)', '경기도 수원시 장안구 (4111100000)',
       '경기도 수원시 권선구 (4111300000)', '경기도 수원시 팔달구 (4111500000)',
       '경기도 수원시 영통구 (4111700000)', '경기도 성남시 (4113000000)',
       '경기도 성남시 수정구 (4113100000)', '경기도 성남시 중원구 (4113300000)',
       '경기도 성남시 분당구 (4113500000)', '의정부시', '경기도 안양시 (4117000000)',
       '경기도 안양시 만안구 (4117100000)', '경기도 안양시 동안구 (4117300000)',
       '경기도 부천시 (4119000000)', '경기도 부천시 원미구 (4119200000)',
       '경기도 부천시 소사구 (4119400000)', '경기도 부천시 오정구 (4119600000)', '광명시',
       '평택시', '동두천시', '경기도 안산시 (4127000000)', '경기도 안산시 상록구 (4127100000)',
       '경기도 안산시 단원구 (4127300000)', '경기도 고양시 (4128000000)',
       '경기도 고양시 덕양구 (4128100000)', '경기도 고양시 일산동구 (4128500000)',
       '경기도 고양시 일산서구 (4128700000)', '과천시', '구리시', '남양주시', '오산시', '시흥시',
       '군포시', '의왕시', '하남시', '경기도 용인시 (4146000000)',
       '경기도 용인시 처인구 (4146100000)', '경기도 용인시 기흥구 (4146300000)',
       '경기도 용인시 수지구 (4146500000)', '파주시', '이천시', '안성시', '김포시', '화성시',
       '광주시', '양주시', '포천시', '여주시', '연천군', '가평군', '양평군',
       '강원특별자치도  (5100000000)', '춘천시', '원주시', '강릉시', '동해시', '태백시', '속초시',
       '삼척시', '홍천군', '횡성군', '영월군', '평창군', '정선군', '철원군', '화천군', '양구군',
       '인제군', '고성군', '양양군', '충청북도  (4300000000)', '충청북도 청주시 (4311000000)',
       '충청북도 청주시 상당구 (4311100000)', '충청북도 청주시 서원구 (4311200000)',
       '충청북도 청주시 흥덕구 (4311300000)', '충청북도 청주시 청원구 (4311400000)', '충주시',
       '제천시', '보은군', '옥천군', '영동군', '증평군', '진천군', '괴산군', '음성군', '단양군',
       '충청남도  (4400000000)', '충청남도 천안시 (4413000000)',
       '충청남도 천안시 동남구 (4413100000)', '충청남도 천안시 서북구 (4413300000)', '공주시',
       '보령시', '아산시', '서산시', '논산시', '계룡시', '당진시', '금산군', '부여군', '서천군',
       '청양군', '홍성군', '예산군', '태안군', '전북특별자치도  (5200000000)',
       '전북특별자치도 전주시 (5211000000)', '전북특별자치도 전주시 완산구 (5211100000)',
       '전북특별자치도 전주시 덕진구 (5211300000)', '군산시', '익산시', '정읍시', '남원시', '김제시',
       '완주군', '진안군', '무주군', '장수군', '임실군', '순창군', '고창군', '부안군',
       '전라남도  (4600000000)', '목포시', '여수시', '순천시', '나주시', '광양시', '담양군',
       '곡성군', '구례군', '고흥군', '보성군', '화순군', '장흥군', '강진군', '해남군', '영암군',
       '무안군', '함평군', '영광군', '장성군', '완도군', '진도군', '신안군',
       '경상북도  (4700000000)', '경상북도 포항시 (4711000000)',
       '경상북도 포항시 남구 (4711100000)', '경상북도 포항시 북구 (4711300000)', '경주시',
       '김천시', '안동시', '구미시', '영주시', '영천시', '상주시', '문경시', '경산시', '의성군',
       '청송군', '영양군', '영덕군', '청도군', '고령군', '성주군', '칠곡군', '예천군', '봉화군',
       '울진군', '울릉군', '경상남도  (4800000000)', '경상남도 창원시 (4812000000)',
       '경상남도 창원시 의창구 (4812100000)', '경상남도 창원시 성산구 (4812300000)',
       '경상남도 창원시 마산합포구 (4812500000)', '경상남도 창원시 마산회원구 (4812700000)',
       '경상남도 창원시 진해구 (4812900000)', '진주시', '통영시', '사천시', '김해시', '밀양시',
       '거제시', '양산시', '의령군', '함안군', '창녕군', '남해군', '하동군', '산청군', '함양군',
       '거창군', '합천군', '제주특별자치도  (5000000000)', '제주시', '서귀포시'], dtype=object)

In [172]:
def replace_seoul_districts(original_list):
    # 새로운 리스트를 저장할 빈 리스트 생성
    new_list = []
    
    for item in original_list:
        # '서울특별시'가 포함되어 있으면
        if '서울특별시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('서울특별시 ', '').split(' (')[0]
            new_list.append(new_item)
        else:
            # '서울특별시'가 포함되어 있지 않으면 원래 문자열을 그대로 추가
            new_list.append(item)
    
    return new_list

In [173]:
updated_list = replace_seoul_districts(new_list)
updated_list

['',
 '종로구',
 '중구',
 '용산구',
 '성동구',
 '광진구',
 '동대문구',
 '중랑구',
 '성북구',
 '강북구',
 '도봉구',
 '노원구',
 '은평구',
 '서대문구',
 '마포구',
 '양천구',
 '강서구',
 '구로구',
 '금천구',
 '영등포구',
 '동작구',
 '관악구',
 '서초구',
 '강남구',
 '송파구',
 '강동구',
 '부산광역시  (2600000000)',
 '부산광역시 중구 (2611000000)',
 '부산광역시 서구 (2614000000)',
 '부산광역시 동구 (2617000000)',
 '부산광역시 영도구 (2620000000)',
 '부산광역시 부산진구 (2623000000)',
 '부산광역시 동래구 (2626000000)',
 '부산광역시 남구 (2629000000)',
 '부산광역시 북구 (2632000000)',
 '부산광역시 해운대구 (2635000000)',
 '부산광역시 사하구 (2638000000)',
 '부산광역시 금정구 (2641000000)',
 '부산광역시 강서구 (2644000000)',
 '부산광역시 연제구 (2647000000)',
 '부산광역시 수영구 (2650000000)',
 '부산광역시 사상구 (2653000000)',
 '부산광역시 기장군 (2671000000)',
 '대구광역시  (2700000000)',
 '대구광역시 중구 (2711000000)',
 '대구광역시 동구 (2714000000)',
 '대구광역시 서구 (2717000000)',
 '대구광역시 남구 (2720000000)',
 '대구광역시 북구 (2723000000)',
 '대구광역시 수성구 (2726000000)',
 '대구광역시 달서구 (2729000000)',
 '대구광역시 달성군 (2771000000)',
 '대구광역시 군위군 (2772000000)',
 '인천광역시  (2800000000)',
 '인천광역시 중구 (2811000000)',
 '인천광역시 동구 (2814000000)',
 '인천광역시 미추홀구 (2817700000)',
 '인천광역시 연수구 (2818500000)',
 '인천광역시 남동구 (2820000000)',
 '인천광역시 부평구 (2823700000)',
 '인천광역시 계양구 (2824500000)',
 '인천광역시 서구 (2826000000)',
 '인천광역시 강화군 (2871000000)',
 '인천광역시 옹진군 (2872000000)',
 '광주광역시  (2900000000)',
 '광주광역시 동구 (2911000000)',
 '광주광역시 서구 (2914000000)',
 '광주광역시 남구 (2915500000)',
 '광주광역시 북구 (2917000000)',
 '광주광역시 광산구 (2920000000)',
 '대전광역시  (3000000000)',
 '대전광역시 동구 (3011000000)',
 '대전광역시 중구 (3014000000)',
 '대전광역시 서구 (3017000000)',
 '대전광역시 유성구 (3020000000)',
 '대전광역시 대덕구 (3023000000)',
 '울산광역시  (3100000000)',
 '울산광역시 중구 (3111000000)',
 '울산광역시 남구 (3114000000)',
 '울산광역시 동구 (3117000000)',
 '울산광역시 북구 (3120000000)',
 '울산광역시 울주군 (3171000000)',
 '세종특별자치시  (3600000000)',
 '세종특별자치시  (3611000000)',
 '경기도  (4100000000)',
 '경기도 수원시 (4111000000)',
 '경기도 수원시 장안구 (4111100000)',
 '경기도 수원시 권선구 (4111300000)',
 '경기도 수원시 팔달구 (4111500000)',
 '경기도 수원시 영통구 (4111700000)',
 '경기도 성남시 (4113000000)',
 '경기도 성남시 수정구 (4113100000)',
 '경기도 성남시 중원구 (4113300000)',
 '경기도 성남시 분당구 (4113500000)',
 '경기도 의정부시 (4115000000)',
 '경기도 안양시 (4117000000)',
 '경기도 안양시 만안구 (4117100000)',
 '경기도 안양시 동안구 (4117300000)',
 '경기도 부천시 (4119000000)',
 '경기도 부천시 원미구 (4119200000)',
 '경기도 부천시 소사구 (4119400000)',
 '경기도 부천시 오정구 (4119600000)',
 '경기도 광명시 (4121000000)',
 '경기도 평택시 (4122000000)',
 '경기도 동두천시 (4125000000)',
 '경기도 안산시 (4127000000)',
 '경기도 안산시 상록구 (4127100000)',
 '경기도 안산시 단원구 (4127300000)',
 '경기도 고양시 (4128000000)',
 '경기도 고양시 덕양구 (4128100000)',
 '경기도 고양시 일산동구 (4128500000)',
 '경기도 고양시 일산서구 (4128700000)',
 '경기도 과천시 (4129000000)',
 '경기도 구리시 (4131000000)',
 '경기도 남양주시 (4136000000)',
 '경기도 오산시 (4137000000)',
 '경기도 시흥시 (4139000000)',
 '경기도 군포시 (4141000000)',
 '경기도 의왕시 (4143000000)',
 '경기도 하남시 (4145000000)',
 '경기도 용인시 (4146000000)',
 '경기도 용인시 처인구 (4146100000)',
 '경기도 용인시 기흥구 (4146300000)',
 '경기도 용인시 수지구 (4146500000)',
 '경기도 파주시 (4148000000)',
 '경기도 이천시 (4150000000)',
 '경기도 안성시 (4155000000)',
 '경기도 김포시 (4157000000)',
 '경기도 화성시 (4159000000)',
 '경기도 광주시 (4161000000)',
 '경기도 양주시 (4163000000)',
 '경기도 포천시 (4165000000)',
 '경기도 여주시 (4167000000)',
 '경기도 연천군 (4180000000)',
 '경기도 가평군 (4182000000)',
 '경기도 양평군 (4183000000)',
 '강원특별자치도  (5100000000)',
 '강원특별자치도 춘천시 (5111000000)',
 '강원특별자치도 원주시 (5113000000)',
 '강원특별자치도 강릉시 (5115000000)',
 '강원특별자치도 동해시 (5117000000)',
 '강원특별자치도 태백시 (5119000000)',
 '강원특별자치도 속초시 (5121000000)',
 '강원특별자치도 삼척시 (5123000000)',
 '강원특별자치도 홍천군 (5172000000)',
 '강원특별자치도 횡성군 (5173000000)',
 '강원특별자치도 영월군 (5175000000)',
 '강원특별자치도 평창군 (5176000000)',
 '강원특별자치도 정선군 (5177000000)',
 '강원특별자치도 철원군 (5178000000)',
 '강원특별자치도 화천군 (5179000000)',
 '강원특별자치도 양구군 (5180000000)',
 '강원특별자치도 인제군 (5181000000)',
 '강원특별자치도 고성군 (5182000000)',
 '강원특별자치도 양양군 (5183000000)',
 '충청북도  (4300000000)',
 '충청북도 청주시 (4311000000)',
 '충청북도 청주시 상당구 (4311100000)',
 '충청북도 청주시 서원구 (4311200000)',
 '충청북도 청주시 흥덕구 (4311300000)',
 '충청북도 청주시 청원구 (4311400000)',
 '충청북도 충주시 (4313000000)',
 '충청북도 제천시 (4315000000)',
 '충청북도 보은군 (4372000000)',
 '충청북도 옥천군 (4373000000)',
 '충청북도 영동군 (4374000000)',
 '충청북도 증평군 (4374500000)',
 '충청북도 진천군 (4375000000)',
 '충청북도 괴산군 (4376000000)',
 '충청북도 음성군 (4377000000)',
 '충청북도 단양군 (4380000000)',
 '충청남도  (4400000000)',
 '충청남도 천안시 (4413000000)',
 '충청남도 천안시 동남구 (4413100000)',
 '충청남도 천안시 서북구 (4413300000)',
 '충청남도 공주시 (4415000000)',
 '충청남도 보령시 (4418000000)',
 '충청남도 아산시 (4420000000)',
 '충청남도 서산시 (4421000000)',
 '충청남도 논산시 (4423000000)',
 '충청남도 계룡시 (4425000000)',
 '충청남도 당진시 (4427000000)',
 '충청남도 금산군 (4471000000)',
 '충청남도 부여군 (4476000000)',
 '충청남도 서천군 (4477000000)',
 '충청남도 청양군 (4479000000)',
 '충청남도 홍성군 (4480000000)',
 '충청남도 예산군 (4481000000)',
 '충청남도 태안군 (4482500000)',
 '전북특별자치도  (5200000000)',
 '전북특별자치도 전주시 (5211000000)',
 '전북특별자치도 전주시 완산구 (5211100000)',
 '전북특별자치도 전주시 덕진구 (5211300000)',
 '전북특별자치도 군산시 (5213000000)',
 '전북특별자치도 익산시 (5214000000)',
 '전북특별자치도 정읍시 (5218000000)',
 '전북특별자치도 남원시 (5219000000)',
 '전북특별자치도 김제시 (5221000000)',
 '전북특별자치도 완주군 (5271000000)',
 '전북특별자치도 진안군 (5272000000)',
 '전북특별자치도 무주군 (5273000000)',
 '전북특별자치도 장수군 (5274000000)',
 '전북특별자치도 임실군 (5275000000)',
 '전북특별자치도 순창군 (5277000000)',
 '전북특별자치도 고창군 (5279000000)',
 '전북특별자치도 부안군 (5280000000)',
 '전라남도  (4600000000)',
 '전라남도 목포시 (4611000000)',
 '전라남도 여수시 (4613000000)',
 '전라남도 순천시 (4615000000)',
 '전라남도 나주시 (4617000000)',
 '전라남도 광양시 (4623000000)',
 '전라남도 담양군 (4671000000)',
 '전라남도 곡성군 (4672000000)',
 '전라남도 구례군 (4673000000)',
 '전라남도 고흥군 (4677000000)',
 '전라남도 보성군 (4678000000)',
 '전라남도 화순군 (4679000000)',
 '전라남도 장흥군 (4680000000)',
 '전라남도 강진군 (4681000000)',
 '전라남도 해남군 (4682000000)',
 '전라남도 영암군 (4683000000)',
 '전라남도 무안군 (4684000000)',
 '전라남도 함평군 (4686000000)',
 '전라남도 영광군 (4687000000)',
 '전라남도 장성군 (4688000000)',
 '전라남도 완도군 (4689000000)',
 '전라남도 진도군 (4690000000)',
 '전라남도 신안군 (4691000000)',
 '경상북도  (4700000000)',
 '경상북도 포항시 (4711000000)',
 '경상북도 포항시 남구 (4711100000)',
 '경상북도 포항시 북구 (4711300000)',
 '경상북도 경주시 (4713000000)',
 '경상북도 김천시 (4715000000)',
 '경상북도 안동시 (4717000000)',
 '경상북도 구미시 (4719000000)',
 '경상북도 영주시 (4721000000)',
 '경상북도 영천시 (4723000000)',
 '경상북도 상주시 (4725000000)',
 '경상북도 문경시 (4728000000)',
 '경상북도 경산시 (4729000000)',
 '경상북도 의성군 (4773000000)',
 '경상북도 청송군 (4775000000)',
 '경상북도 영양군 (4776000000)',
 '경상북도 영덕군 (4777000000)',
 '경상북도 청도군 (4782000000)',
 '경상북도 고령군 (4783000000)',
 '경상북도 성주군 (4784000000)',
 '경상북도 칠곡군 (4785000000)',
 '경상북도 예천군 (4790000000)',
 '경상북도 봉화군 (4792000000)',
 '경상북도 울진군 (4793000000)',
 '경상북도 울릉군 (4794000000)',
 '경상남도  (4800000000)',
 '경상남도 창원시 (4812000000)',
 '경상남도 창원시 의창구 (4812100000)',
 '경상남도 창원시 성산구 (4812300000)',
 '경상남도 창원시 마산합포구 (4812500000)',
 '경상남도 창원시 마산회원구 (4812700000)',
 '경상남도 창원시 진해구 (4812900000)',
 '경상남도 진주시 (4817000000)',
 '경상남도 통영시 (4822000000)',
 '경상남도 사천시 (4824000000)',
 '경상남도 김해시 (4825000000)',
 '경상남도 밀양시 (4827000000)',
 '경상남도 거제시 (4831000000)',
 '경상남도 양산시 (4833000000)',
 '경상남도 의령군 (4872000000)',
 '경상남도 함안군 (4873000000)',
 '경상남도 창녕군 (4874000000)',
 '경상남도 고성군 (4882000000)',
 '경상남도 남해군 (4884000000)',
 '경상남도 하동군 (4885000000)',
 '경상남도 산청군 (4886000000)',
 '경상남도 함양군 (4887000000)',
 '경상남도 거창군 (4888000000)',
 '경상남도 합천군 (4889000000)',
 '제주특별자치도  (5000000000)',
 '제주특별자치도 제주시 (5011000000)',
 '제주특별자치도 서귀포시 (5013000000)']

In [191]:
updated_list[0] = '서울'

In [204]:
len(updated_list)

328

In [199]:
df_pop["시군구코드명"] = updated_list

ValueError: Length of values (328) does not match length of index (281)

In [ ]:
df_pop["시군구코드명"]

In [215]:
df_pop.to_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별인구_2024수정본.csv")

In [158]:
original_list.tolist

In [167]:
import numpy as np
original_list = np.setdiff1d(original_list, updated_list)

In [168]:
original_list

array(['가평군', '강릉시', '강진군', '거제시', '거창군', '경산시', '경주시', '계룡시', '고령군',
       '고성군', '고양덕양구', '고양일산동구', '고양일산서구', '고창군', '고흥군', '곡성군', '공주시',
       '과천시', '광명시', '광양시', '광주광산구', '광주남구', '광주동구', '광주북구', '광주서구',
       '광주시', '괴산군', '구례군', '구리시', '구미시', '군산시', '군포시', '금산군', '김제시',
       '김천시', '김포시', '김해시', '나주시', '남양주시', '남원시', '남해군', '논산시', '단양군',
       '담양군', '당진시', '대구군위군', '대구남구', '대구달서구', '대구달성군', '대구동구', '대구북구',
       '대구서구', '대구수성구', '대구중구', '대전대덕구', '대전동구', '대전서구', '대전유성구', '대전중구',
       '동두천시', '동해시', '목포시', '무안군', '무주군', '문경시', '밀양시', '보령시', '보성군',
       '보은군', '봉화군', '부산강서구', '부산금정구', '부산기장군', '부산남구', '부산동구', '부산동래구',
       '부산북구', '부산사상구', '부산사하구', '부산서구', '부산수영구', '부산연제구', '부산영도구',
       '부산중구', '부산진구', '부산해운대구', '부안군', '부여군', '부천소사구', '부천오정구', '부천원미구',
       '사천시', '산청군', '삼척시', '상주시', '서귀포시', '서산시', '서천군', '성남분당구', '성남수정구',
       '성남중원구', '성주군', '세종시', '속초시', '수원권선구', '수원영통구', '수원장안구', '수원팔달구',
       '순창군', '순천시', '시흥시', '신안군', '아산시', '안동시', '안산단원구', '안산상록구', '안성시',
       '안양동안구', '안양만안구', '양구군', '양산시', '양양군', '양주시', '양평군', '여수시', '여주시',
       '연천군', '영광군', '영덕군', '영동군', '영암군', '영양군', '영월군', '영주시', '영천시',
       '예산군', '예천군', '오산시', '옥천군', '완도군', '완주군', '용인기흥구', '용인수지구',
       '용인처인구', '울릉군', '울산남구', '울산동구', '울산북구', '울산울주군', '울산중구', '울진군',
       '원주시', '음성군', '의령군', '의성군', '의왕시', '의정부시', '이천시', '익산시', '인제군',
       '인천강화군', '인천계양구', '인천남동구', '인천동구', '인천미추홀구', '인천부평구', '인천서구',
       '인천연수구', '인천옹진군', '인천중구', '임실군', '장성군', '장수군', '장흥군', '전주덕진구',
       '전주완산구', '정선군', '정읍시', '제주시', '제천시', '증평군', '진도군', '진안군', '진주시',
       '진천군', '창녕군', '창원마산합포구', '창원마산회원구', '창원성산구', '창원의창구', '창원진해구',
       '천안동남구', '천안서북구', '철원군', '청도군', '청송군', '청양군', '청주상당구', '청주서원구',
       '청주청원구', '청주흥덕구', '춘천시', '충주시', '칠곡군', '태백시', '태안군', '통영시', '파주시',
       '평창군', '평택시', '포천시', '포항남구', '포항북구', '하남시', '하동군', '함안군', '함양군',
       '함평군', '합천군', '해남군', '홍성군', '홍천군', '화성시', '화순군', '화천군', '횡성군'],
      dtype=object)

In [251]:
def replace_city_districts(original_list):
    # 새로운 리스트를 저장할 빈 리스트 생성
    new_list = []
    
    for item in original_list:
        # '서울특별시'가 포함되어 있으면
        if '부산광역시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('부산광역시 ', '').split(' (')[0]
            new_list.append("부산"+new_item)
        elif '인천광역시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('인천광역시 ', '').split(' (')[0]
            new_list.append("인천"+new_item)
        elif '대구광역시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('대구광역시 ', '').split(' (')[0]
            new_list.append("대구"+new_item)
        elif '광주광역시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('광주광역시 ', '').split(' (')[0]
            new_list.append("광주"+new_item)
        elif '울산광역시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('울산광역시 ', '').split(' (')[0]
            new_list.append("울산"+new_item)
        elif '대전광역시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('대전광역시 ', '').split(' (')[0]
            new_list.append("대전"+new_item)
        elif '세종특별자치시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('세종특별자치시 ', '').split(' (')[0]
            new_list.append("세종시"+new_item)
        elif '경기도' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('경기도 ', '').split(' (')[0]
            new_list.append(new_item)
        elif '충청북도' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('충청북도 ', '').split(' (')[0]
            new_list.append(new_item)
        elif '충청남도' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('충청남도 ', '').split(' (')[0]
            new_list.append(new_item)
        elif '전북특별자치도' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('전북특별자치도 ', '').split(' (')[0]
            new_list.append(new_item)
        elif '경상북도' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('경상북도 ', '').split(' (')[0]
            new_list.append(new_item)
        elif '경상남도' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('경상남도 ', '').split(' (')[0]
            new_list.append(new_item)
        elif '제주특별자치도' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('제주특별자치도 ', '').split(' (')[0]
            new_list.append("제주"+new_item)
        else:
            # '서울특별시'가 포함되어 있지 않으면 원래 문자열을 그대로 추가
            new_list.append(item)
    
    return new_list

In [248]:
final_list[271]

'고성군'

In [276]:
final_list = replace_city_districts(final_list)
final_list

['서울',
 '종로구',
 '중구',
 '용산구',
 '성동구',
 '광진구',
 '동대문구',
 '중랑구',
 '성북구',
 '강북구',
 '도봉구',
 '노원구',
 '은평구',
 '서대문구',
 '마포구',
 '양천구',
 '강서구',
 '구로구',
 '금천구',
 '영등포구',
 '동작구',
 '관악구',
 '서초구',
 '강남구',
 '송파구',
 '강동구',
 '부산',
 '부산중구',
 '부산서구',
 '부산동구',
 '부산영도구',
 '부산진구',
 '부산동래구',
 '부산남구',
 '부산북구',
 '부산해운대구',
 '부산사하구',
 '부산금정구',
 '부산강서구',
 '부산연제구',
 '부산수영구',
 '부산사상구',
 '부산기장군',
 '대구',
 '대구중구',
 '대구동구',
 '대구서구',
 '대구남구',
 '대구북구',
 '대구수성구',
 '대구달서구',
 '대구달성군',
 '대구군위군',
 '인천',
 '인천중구',
 '인천동구',
 '인천미추홀구',
 '인천연수구',
 '인천남동구',
 '인천부평구',
 '인천계양구',
 '인천서구',
 '인천강화군',
 '인천옹진군',
 '광주',
 '광주동구',
 '광주서구',
 '광주남구',
 '광주북구',
 '광주광산구',
 '대전',
 '대전동구',
 '대전중구',
 '대전서구',
 '대전유성구',
 '대전대덕구',
 '울산',
 '울산중구',
 '울산남구',
 '울산동구',
 '울산북구',
 '울산울주군',
 '세종시',
 '세종시',
 '경기',
 '수원수원시',
 '수원장안구',
 '수원권선구',
 '수원팔달구',
 '수원영통구',
 '성남성남시',
 '성남수정구',
 '성남중원구',
 '성남분당구',
 '의정부시',
 '안양안양시',
 '안양만안구',
 '안양동안구',
 '부천부천시',
 '부천원미구',
 '부천소사구',
 '부천오정구',
 '광명시',
 '평택시',
 '동두천시',
 '안산안산시',
 '안산상록구',
 '안산단원구',
 '고양고양시',
 '고양덕양구',
 '고양일산동구',
 '고양일산서구',
 '과천시',
 '구리시',
 '남양주시',
 '오산시',
 '시흥시',
 '군포시',
 '의왕시',
 '하남시',
 '용인용인시',
 '용인처인구',
 '용인기흥구',
 '용인수지구',
 '파주시',
 '이천시',
 '안성시',
 '김포시',
 '화성시',
 '광주시',
 '양주시',
 '포천시',
 '여주시',
 '연천군',
 '가평군',
 '양평군',
 '강원',
 '춘천시',
 '원주시',
 '강릉시',
 '동해시',
 '태백시',
 '속초시',
 '삼척시',
 '홍천군',
 '횡성군',
 '영월군',
 '평창군',
 '정선군',
 '철원군',
 '화천군',
 '양구군',
 '인제군',
 '고성군',
 '양양군',
 '충북',
 '청주청주시',
 '청주상당구',
 '청주서원구',
 '청주흥덕구',
 '청주청원구',
 '충주시',
 '제천시',
 '보은군',
 '옥천군',
 '영동군',
 '증평군',
 '진천군',
 '괴산군',
 '음성군',
 '단양군',
 '충남',
 '천안천안시',
 '천안동남구',
 '천안서북구',
 '공주시',
 '보령시',
 '아산시',
 '서산시',
 '논산시',
 '계룡시',
 '당진시',
 '금산군',
 '부여군',
 '서천군',
 '청양군',
 '홍성군',
 '예산군',
 '태안군',
 '전북',
 '전주전주시',
 '전주완산구',
 '전주덕진구',
 '군산시',
 '익산시',
 '정읍시',
 '남원시',
 '김제시',
 '완주군',
 '진안군',
 '무주군',
 '장수군',
 '임실군',
 '순창군',
 '고창군',
 '부안군',
 '전남',
 '목포시',
 '여수시',
 '순천시',
 '나주시',
 '광양시',
 '담양군',
 '곡성군',
 '구례군',
 '고흥군',
 '보성군',
 '화순군',
 '장흥군',
 '강진군',
 '해남군',
 '영암군',
 '무안군',
 '함평군',
 '영광군',
 '장성군',
 '완도군',
 '진도군',
 '신안군',
 '경북',
 '포항포항시',
 '포항남구',
 '포항북구',
 '경주시',
 '김천시',
 '안동시',
 '구미시',
 '영주시',
 '영천시',
 '상주시',
 '문경시',
 '경산시',
 '의성군',
 '청송군',
 '영양군',
 '영덕군',
 '청도군',
 '고령군',
 '성주군',
 '칠곡군',
 '예천군',
 '봉화군',
 '울진군',
 '울릉군',
 '경남',
 '창원창원시',
 '창원의창구',
 '창원성산구',
 '창원마산합포구',
 '창원마산회원구',
 '창원진해구',
 '진주시',
 '통영시',
 '사천시',
 '김해시',
 '밀양시',
 '거제시',
 '양산시',
 '의령군',
 '함안군',
 '창녕군',
 '고성군',
 '남해군',
 '하동군',
 '산청군',
 '함양군',
 '거창군',
 '합천군',
 '제주',
 '제주시',
 '서귀포시']

In [226]:
name = df_pop["시군구코드명"]

print(set(final_list)-(set(name)))

{'', '인천', '부산서구', '부천시 오정구', '인천부평구', '인천강화군', '창원시 의창구', '성남시 중원구', '고양시 일산서구', '대전유성구', '청주시 상당구', '부산남구', '전주시 덕진구', '천안시 서북구', '수원시 팔달구', '수원시', '청주시 청원구', '인천동구', '성남시 분당구', '포항시 남구', '안산시 상록구', '울산남구', '부산금정구', '대전동구', '부산수영구', '제주', '청주시 서원구', '부산사하구', '대전중구', '부산해운대구', '울산북구', '인천미추홀구', '포항시', '안산시', '수원시 권선구', '부산강서구', '용인시', '세종시', '광주남구', '부산사상구', '고양시 덕양구', '인천서구', '용인시 수지구', '용인시 처인구', '부산동래구', '천안시 동남구', '부산기장군', '성남시', '부천시 원미구', '부산동구', '수원시 영통구', '부산연제구', '울산동구', '창원시', '창원시 마산회원구', '인천계양구', '안양시 동안구', '광주서구', '청주시', '부산북구', '광주동구', '창원시 성산구', '안산시 단원구', '광주', '부산', '창원시 진해구', '인천남동구', '천안시', '수원시 장안구', '용인시 기흥구', '고양시', '인천옹진군', '부산영도구', '성남시 수정구', '전주시 완산구', '대전서구', '울산중구', '안양시', '포항시 북구', '울산', '대전', '부산중구', '고양시 일산동구', '대전대덕구', '부천시', '광주북구', '인천중구', '울산울주군', '안양시 만안구', '광주광산구', '부천시 소사구', '전주시', '청주시 흥덕구', '인천연수구', '창원시 마산합포구'}

In [258]:
df_pop = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별인구_2024수정본.csv")
df_pop

     Unnamed: 0.1  Unnamed: 0 시군구코드명 2024년09월_계_총인구수   0
0               0           0     서울       9,350,995  서울
1               1           1    종로구         138,879  서울
2               2           2     중구         121,324  서울
3               3           3    용산구         205,145  서울
4               4           4    성동구         275,403  서울
..            ...         ...    ...             ...  ..
276           276         276    거창군          59,737  서울
277           277         277    합천군          40,440  서울
278           278         278     제주         671,064  서울
279           279         279    제주시         488,844  서울
280           280         280   서귀포시         182,220  서울

[281 rows x 5 columns]

In [277]:
df_pop["시군구코드명"] = final_list

In [278]:
df_pop.to_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별인구_2024수정본.csv")

In [261]:
df_pop = df_pop.drop(columns=['Unnamed: 0.1'])

In [263]:
final_list = df_pop["시군구코드명"]

In [271]:
final_list[254] = '경남'

In [275]:
def replace_city_districts(original_list):
    # 새로운 리스트를 저장할 빈 리스트 생성
    new_list = []
    
    for item in original_list:
        # '서울특별시'가 포함되어 있으면
        if '수원시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('수원시 ', '')
            new_list.append("수원"+new_item)
        elif '성남시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('성남시 ', '')
            new_list.append("성남"+new_item)
        elif '안양시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('안양시 ', '')
            new_list.append("안양"+new_item)
        elif '부천시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('부천시 ', '')
            new_list.append("부천"+new_item)
        elif '안산시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('안산시 ', '')
            new_list.append("안산"+new_item)
        elif '고양시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('고양시 ', '')
            new_list.append("고양"+new_item)
        elif '용인시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('용인시 ', '')
            new_list.append("용인"+new_item)
        elif '청주시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('청주시 ', '')
            new_list.append("청주"+new_item)
        elif '천안시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('천안시 ', '')
            new_list.append("천안"+new_item)
        elif '전주시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('전주시 ', '')
            new_list.append("전주"+new_item)
        elif '포항시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('포항시 ', '')
            new_list.append("포항"+new_item)
        elif '창원시' in item:
            # '서울특별시'를 제거하고, 괄호와 숫자 부분도 제거
            new_item = item.replace('창원시 ', '')
            new_list.append("창원"+new_item)
        else:
            # '서울특별시'가 포함되어 있지 않으면 원래 문자열을 그대로 추가
            new_list.append(item)
    
    return new_list

In [279]:
df_merge = pd.merge(df_hos, df_pop, how='left', on='시군구코드명')

In [280]:
df_merge

,Unnamed: 0,암호화요양기호,요양기관명,종별코드명,설립구분코드명,시도코드명,시군구코드명,개설일자,성인중환자병상수,일반입원실병상수,...,치과레지던트 인원수,치과전문의 인원수,한방일반의 인원수,한방인턴 인원수,한방레지던트 인원수,한방전문의 인원수,조산사 인원수,진료과목코드명,과목별 전문의수,2024년09월_계_총인구수
0,0,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,0,...,0,0,0,0,0,0,0,내과,0.0,"94,808"
1,1,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,0,...,0,0,0,0,0,0,0,마취통증의학과,0.0,"94,808"
2,2,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,0,...,0,0,0,0,0,0,0,신경외과,0.0,"94,808"
3,3,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,0,...,0,0,0,0,0,0,0,외과,1.0,"94,808"
4,4,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,0,...,0,0,0,0,0,0,0,재활의학과,0.0,"94,808"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410564,407395,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,0,...,0,0,1,0,0,0,0,한방부인과,0.0,"414,883"
410565,407396,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,0,...,0,0,1,0,0,0,0,한방소아과,0.0,"414,883"
410566,407397,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,0,...,0,0,1,0,0,0,0,한방신경정신과,0.0,"414,883"
410567,407398,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,0,...,0,0,1,0,0,0,0,한방안·이비인후·피부과,0.0,"414,883"
410568,407399,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,0,...,0,0,1,0,0,0,0,한방재활의학과,0.0,"414,883"

In [289]:
df_merge.to_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별 인구&병원.csv")

In [287]:
df_merge = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별 인구&병원.csv")
df_merge

,Unnamed: 0,Unnamed: 0.1,암호화요양기호,요양기관명,종별코드명,설립구분코드명,시도코드명,시군구코드명,개설일자,성인중환자병상수,...,치과레지던트 인원수,치과전문의 인원수,한방일반의 인원수,한방인턴 인원수,한방레지던트 인원수,한방전문의 인원수,조산사 인원수,진료과목코드명,과목별 전문의수,2024년09월_계_총인구수
0,0,0,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,0,0,0,0,0,0,0,내과,0.0,"94,808"
1,1,1,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,0,0,0,0,0,0,0,마취통증의학과,0.0,"94,808"
2,2,2,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,0,0,0,0,0,0,0,신경외과,0.0,"94,808"
3,3,3,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,0,0,0,0,0,0,0,외과,1.0,"94,808"
4,4,4,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,0,0,0,0,0,0,0,재활의학과,0.0,"94,808"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410564,410564,410564,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,0,0,1,0,0,0,0,한방부인과,0.0,"414,883"
410565,410565,410565,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,0,0,1,0,0,0,0,한방소아과,0.0,"414,883"
410566,410566,410566,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,0,0,1,0,0,0,0,한방신경정신과,0.0,"414,883"
410567,410567,410567,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,0,0,1,0,0,0,0,한방안·이비인후·피부과,0.0,"414,883"
410568,410568,410568,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,0,0,1,0,0,0,0,한방재활의학과,0.0,"414,883"

In [288]:
df_merge = df_merge.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])

In [291]:
df_merge.to_excel("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/엑셀.xlsx")

In [292]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별 인구&병원.csv")
df["시군구코드명"]

0         대구중구
1         대구중구
2         대구중구
3         대구중구
4         대구중구
          ...
410564    대구북구
410565    대구북구
410566    대구북구
410567    대구북구
410568    대구북구
Name: 시군구코드명, Length: 410569, dtype: object

In [294]:
df["시군구코드명"].unique()

array(['대구중구', '구리시', '성남수정구', '고양덕양구', '대전중구', '부산금정구', '부천원미구', '대전유성구',
       '부산동래구', '파주시', '부천소사구', '세종시', '광주시', '천안서북구', '금천구', '서초구',
       '시흥시', '전주완산구', '광진구', '거제시', '영주시', '강남구', '마포구', '도봉구', '성동구',
       '양주시', '부산서구', '광주광산구', '울산중구', '부산동구', '화성시', '군포시', '보령시',
       '고양일산서구', '고양일산동구', '인천서구', '평택시', '칠곡군', '동대문구', '대구수성구', '부산남구',
       '안산단원구', '안산상록구', '인천미추홀구', '창원마산회원구', '울산남구', '송파구', '성남분당구',
       '부산해운대구', '동작구', '용인기흥구', '광주북구', '은평구', '대구달서구', '인천중구', '대구북구',
       '용인수지구', '용인처인구', '김포시', '안양동안구', '부산진구', '양산시', '광주서구', '옥천군',
       '용산구', '남양주시', '창원진해구', '부산수영구', '제주시', '김해시', '수원권선구', '대전대덕구',
       '중랑구', '충주시', '수원영통구', '대구달성군', '철원군', '인천남동구', '노원구', '대구남구',
       '산청군', '관악구', '광주남구', '수원팔달구', '안양만안구', '포항북구', '대전서구', '강동구',
       '음성군', '여수시', '강서구', '완주군', '경주시', '의성군', '고흥군', '광명시', '하남시',
       '익산시', '영등포구', '서대문구', '동해시', '수원장안구', '청주상당구', '구로구', '춘천시',
       '포항남구', '인천부평구', '성북구', '양천구', '인천계양구', '함양군', '창원성산구', '강북구',
       '당진시', '중구', '서산시', '종로구', '부산연제구', '부산사하구', '해남군', '진주시', '청주서원구',
       '천안동남구', '순천시', '오산시', '의왕시', '부산강서구', '인천연수구', '부산사상구', '김제시',
       '군산시', '정읍시', '순창군', '남원시', '장수군', '진안군', '전주덕진구', '홍성군', '의정부시',
       '경산시', '부산중구', '강릉시', '삼척시', '대구동구', '여주시', '울산북구', '창원의창구', '원주시',
       '남해군', '울산울주군', '고성군', '영천시', '창원마산합포구', '임실군', '부산북구', '부산영도구',
       '강진군', '서귀포시', '부산기장군', '구미시', '양평군', '안성시', '이천시', '가평군', '포천시',
       '부천오정구', '과천시', '고창군', '인천동구', '연천군', '거창군', '성남중원구', '동두천시',
       '인천옹진군', '부안군', '문경시', '논산시', '울진군', '대전동구', '제천시', '나주시', '무안군',
       '함안군', '예산군', '청주흥덕구', '진천군', '청주청원구', '괴산군', '단양군', '금산군', '청양군',
       '태안군', '아산시', '부여군', '서천군', '홍천군', '화천군', '울릉군', '대구서구', '공주시',
       '무주군', '계룡시', '목포시', '광주동구', '담양군', '신안군', '보성군', '곡성군', '광양시',
       '구례군', '장흥군', '안동시', '영광군', '진도군', '함평군', '완도군', '화순군', '장성군',
       '영암군', '창녕군', '영덕군', '상주시', '김천시', '성주군', '인천강화군', '영동군', '태백시',
       '속초시', '양구군', '보은군', '증평군', '대구군위군', '청송군', '횡성군', '인제군', '영월군',
       '예천군', '청도군', '고령군', '영양군', '봉화군', '밀양시', '의령군', '평창군', '울산동구',
       '하동군', '사천시', '정선군', '합천군', '양양군', '통영시'], dtype=object)

In [295]:
df2 = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별인구_2024수정본.csv")
df2["시군구코드명"].unique()

array(['서울', '종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구',
       '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구',
       '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', '부산',
       '부산중구', '부산서구', '부산동구', '부산영도구', '부산진구', '부산동래구', '부산남구', '부산북구',
       '부산해운대구', '부산사하구', '부산금정구', '부산강서구', '부산연제구', '부산수영구', '부산사상구',
       '부산기장군', '대구', '대구중구', '대구동구', '대구서구', '대구남구', '대구북구', '대구수성구',
       '대구달서구', '대구달성군', '대구군위군', '인천', '인천중구', '인천동구', '인천미추홀구', '인천연수구',
       '인천남동구', '인천부평구', '인천계양구', '인천서구', '인천강화군', '인천옹진군', '광주', '광주동구',
       '광주서구', '광주남구', '광주북구', '광주광산구', '대전', '대전동구', '대전중구', '대전서구',
       '대전유성구', '대전대덕구', '울산', '울산중구', '울산남구', '울산동구', '울산북구', '울산울주군',
       '세종시', '경기', '수원수원시', '수원장안구', '수원권선구', '수원팔달구', '수원영통구', '성남성남시',
       '성남수정구', '성남중원구', '성남분당구', '의정부시', '안양안양시', '안양만안구', '안양동안구',
       '부천부천시', '부천원미구', '부천소사구', '부천오정구', '광명시', '평택시', '동두천시', '안산안산시',
       '안산상록구', '안산단원구', '고양고양시', '고양덕양구', '고양일산동구', '고양일산서구', '과천시',
       '구리시', '남양주시', '오산시', '시흥시', '군포시', '의왕시', '하남시', '용인용인시', '용인처인구',
       '용인기흥구', '용인수지구', '파주시', '이천시', '안성시', '김포시', '화성시', '광주시', '양주시',
       '포천시', '여주시', '연천군', '가평군', '양평군', '강원', '춘천시', '원주시', '강릉시',
       '동해시', '태백시', '속초시', '삼척시', '홍천군', '횡성군', '영월군', '평창군', '정선군',
       '철원군', '화천군', '양구군', '인제군', '고성군', '양양군', '충북', '청주청주시', '청주상당구',
       '청주서원구', '청주흥덕구', '청주청원구', '충주시', '제천시', '보은군', '옥천군', '영동군',
       '증평군', '진천군', '괴산군', '음성군', '단양군', '충남', '천안천안시', '천안동남구', '천안서북구',
       '공주시', '보령시', '아산시', '서산시', '논산시', '계룡시', '당진시', '금산군', '부여군',
       '서천군', '청양군', '홍성군', '예산군', '태안군', '전북', '전주전주시', '전주완산구', '전주덕진구',
       '군산시', '익산시', '정읍시', '남원시', '김제시', '완주군', '진안군', '무주군', '장수군',
       '임실군', '순창군', '고창군', '부안군', '전남', '목포시', '여수시', '순천시', '나주시',
       '광양시', '담양군', '곡성군', '구례군', '고흥군', '보성군', '화순군', '장흥군', '강진군',
       '해남군', '영암군', '무안군', '함평군', '영광군', '장성군', '완도군', '진도군', '신안군',
       '경북', '포항포항시', '포항남구', '포항북구', '경주시', '김천시', '안동시', '구미시', '영주시',
       '영천시', '상주시', '문경시', '경산시', '의성군', '청송군', '영양군', '영덕군', '청도군',
       '고령군', '성주군', '칠곡군', '예천군', '봉화군', '울진군', '울릉군', '경남', '창원창원시',
       '창원의창구', '창원성산구', '창원마산합포구', '창원마산회원구', '창원진해구', '진주시', '통영시',
       '사천시', '김해시', '밀양시', '거제시', '양산시', '의령군', '함안군', '창녕군', '남해군',
       '하동군', '산청군', '함양군', '거창군', '합천군', '제주', '제주시', '서귀포시'],
      dtype=object)

In [296]:
import pandas as pd
import numpy as np

In [375]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별 인구&병원.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410569 entries, 0 to 410568
Data columns (total 48 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Unnamed: 0.2     410569 non-null  int64
 1   Unnamed: 0.1     410569 non-null  int64
 2   Unnamed: 0       410569 non-null  int64
 3   암호화요양기호          410569 non-null  object
 4   요양기관명            410569 non-null  object
 5   종별코드명            410569 non-null  object
 6   설립구분코드명          410569 non-null  object
 7   시도코드명            410569 non-null  object
 8   시군구코드명           410569 non-null  object
 9   개설일자             410569 non-null  int64
 10  성인중환자병상수         410569 non-null  int64
 11  일반입원실병상수         410569 non-null  int64
 12  소아중환자병상수         410569 non-null  int64
 13  신생아중환자병상수        410569 non-null  int64
 14  분만실병상수           410569 non-null  int64
 15  수술실병상수           410569 non-null  int64
 16  응급실병상수           410569 non-null  int64
 17  물리치료실병상수         410569 non-null  int64
 18  정신과폐쇄상급병상수       410569 non-null  int64
 19  정신과폐쇄일반병상수       410569 non-null  int64
 20  정신과개방상급병상수       410569 non-null  int64
 21  정신과폐쇄개방병상수       410569 non-null  int64
 22  격리병실병상수          410569 non-null  int64
 23  무균치료실병상수         410569 non-null  int64
 24  총의사수_x           410569 non-null  int64
 25  의과일반의 인원수        410569 non-null  int64
 26  의과인턴 인원수         410569 non-null  int64
 27  의과레지던트 인원수       410569 non-null  int64
 28  의과전문의 인원수        410569 non-null  int64
 29  치과일반의 인원수        410569 non-null  int64
 30  치과인턴 인원수         410569 non-null  int64
 31  치과레지던트 인원수       410569 non-null  int64
 32  치과전문의 인원수        410569 non-null  int64
 33  한방일반의 인원수        410569 non-null  int64
 34  한방인턴 인원수         410569 non-null  int64
 35  한방레지던트 인원수       410569 non-null  int64
 36  한방전문의 인원수        410569 non-null  int64
 37  조산사 인원수          410569 non-null  int64
 38  진료과목코드명          410569 non-null  object
 39  과목별 전문의수         410569 non-null  float64
 40  2024년09월_계_총인구수  410569 non-null  int64
 41  총병상수             410569 non-null  int64
 42  총의사수_y           410569 non-null  int64
 43  총병원수             410569 non-null  int64
 44  총인구수             410569 non-null  float64
 45  인구대비병상수          410569 non-null  float64
 46  인구대비의사수          410569 non-null  float64
 47  인구대비병원수          410569 non-null  float64
dtypes: float64(5), int64(36), object(7)
memory usage: 150.4+ MB

In [300]:
df.isnull().sum()

Unnamed: 0            0
암호화요양기호               0
요양기관명                 0
종별코드명                 0
설립구분코드명               0
시도코드명                 0
시군구코드명                0
개설일자                  0
성인중환자병상수              0
일반입원실병상수              0
소아중환자병상수              0
신생아중환자병상수             0
분만실병상수                0
수술실병상수                0
응급실병상수                0
물리치료실병상수              0
정신과폐쇄상급병상수            0
정신과폐쇄일반병상수            0
정신과개방상급병상수            0
정신과폐쇄개방병상수            0
격리병실병상수               0
무균치료실병상수              0
총의사수                  0
의과일반의 인원수             0
의과인턴 인원수              0
의과레지던트 인원수            0
의과전문의 인원수             0
치과일반의 인원수             0
치과인턴 인원수              0
치과레지던트 인원수            0
치과전문의 인원수             0
한방일반의 인원수             0
한방인턴 인원수              0
한방레지던트 인원수            0
한방전문의 인원수             0
조산사 인원수               0
진료과목코드명            3155
과목별 전문의수           3155
2024년09월_계_총인구수       0
dtype: int64

In [323]:
df.groupby('시도코드명')['요양기관명'].size().reset_index(name='요양기관_개수')

   시도코드명  요양기관_개수
0     강원     9219
1     경기    97145
2     경남    23763
3     경북    15899
4     광주    13151
5     대구    20956
6     대전    13169
7     부산    27806
8     서울    99266
9    세종시     5450
10    울산     6808
11    인천    21536
12    전남    12975
13    전북    13701
14    제주     4735
15    충남    14229
16    충북    10761

In [336]:
df['2024년09월_계_총인구수'] = df['2024년09월_계_총인구수'].astype(str).str.replace(',', '', regex=False).astype(int)

In [342]:
df2 = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/지역별_인구대비_병상의사병원수.csv")

In [343]:
df2.rename(columns={'행정구역': '시도코드명'}, inplace=True)

In [370]:
df2

   시도코드명    총병상수   총의사수   총병원수        총인구수   인구대비병상수   인구대비의사수   인구대비병원수
0     강원   21537   3798   1975   1520410.0  0.014165  0.014165  0.001299
1     경기  177901  35236  17631  13680645.0  0.013004  0.013004  0.001289
2     경남   74417   8144   4228   3232297.0  0.023023  0.023023  0.001308
3     경북   51591   5580   3396   2537955.0  0.020328  0.020328  0.001338
4     광주   46496   5297   2328   1411357.0  0.032944  0.032944  0.001649
5     대구   50793   8345   4151   2365523.0  0.021472  0.021472  0.001755
6     대전   28287   4982   2345   1440456.0  0.019638  0.019638  0.001628
7     부산   83801  11545   5571   3273473.0  0.025600  0.025600  0.001702
8     서울  120961  42011  19158   9350995.0  0.012936  0.012936  0.002049
9    세종시    3210    801    463    389443.0  0.008243  0.008243  0.001189
10    울산   18650   2741   1426   1098728.0  0.016974  0.016974  0.001298
11    인천   45952   8029   3799   3016520.0  0.015233  0.015233  0.001259
12    전남   52520   4664   2622   1791496.0  0.029316  0.029316  0.001464
13    전북   47998   5294   2942   1741640.0  0.027559  0.027559  0.001689
14    제주    7663   1756   1041    671064.0  0.011419  0.011419  0.001551
15    충남   36320   4969   2851   2135373.0  0.017009  0.017009  0.001335
16    충북   27598   3784   2199   1590858.0  0.017348  0.017348  0.001382

In [371]:
result2 = df2[["시도코드명", "인구대비병원수"]]

In [372]:
result2

   시도코드명   인구대비병원수
0     강원  0.001299
1     경기  0.001289
2     경남  0.001308
3     경북  0.001338
4     광주  0.001649
5     대구  0.001755
6     대전  0.001628
7     부산  0.001702
8     서울  0.002049
9    세종시  0.001189
10    울산  0.001298
11    인천  0.001259
12    전남  0.001464
13    전북  0.001689
14    제주  0.001551
15    충남  0.001335
16    충북  0.001382

In [373]:
df_merge = pd.merge(df, df2, how="left", on="시도코드명")
df_merge

,Unnamed: 0.1,Unnamed: 0,암호화요양기호,요양기관명,종별코드명,설립구분코드명,시도코드명,시군구코드명,개설일자,성인중환자병상수,...,진료과목코드명,과목별 전문의수,2024년09월_계_총인구수,총병상수,총의사수_y,총병원수,총인구수,인구대비병상수,인구대비의사수,인구대비병원수
0,0,0,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,내과,0.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755
1,1,1,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,마취통증의학과,0.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755
2,2,2,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,신경외과,0.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755
3,3,3,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,외과,1.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755
4,4,4,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,20230424,0,...,재활의학과,0.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410564,410564,410564,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,한방부인과,0.0,414883,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755
410565,410565,410565,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,한방소아과,0.0,414883,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755
410566,410566,410566,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,한방신경정신과,0.0,414883,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755
410567,410567,410567,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,한방안·이비인후·피부과,0.0,414883,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755
410568,410568,410568,JDQ4MTYyMiM4MSMkMSMkMCMkMTMkNDgxOTYxIzUxIyQxIy...,온유한의원,한의원,개인,대구,대구북구,20230713,0,...,한방재활의학과,0.0,414883,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755

In [374]:
df_merge.to_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별 인구&병원.csv")

In [376]:
hos_count = df.groupby('시군구코드명')['요양기관명'].size().reset_index(name='요양기관수')
hos_count

    시군구코드명  요양기관수
0      가평군    526
1      강남구  12933
2      강동구   4743
3      강릉시   1123
4      강북구   2550
..     ...    ...
246    홍천군    409
247    화성시   5608
248    화순군    577
249    화천군    148
250    횡성군    211

[251 rows x 2 columns]

In [378]:
df2 = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별인구_2024수정본.csv")
df_merge = pd.merge(hos_count, df2, how="left", on="시군구코드명")
df_merge

    시군구코드명  요양기관수  Unnamed: 0 2024년09월_계_총인구수
0      가평군    526         134          62,492
1      강남구  12933          23         558,508
2      강동구   4743          25         465,090
3      강릉시   1123         139         208,161
4      강북구   2550           9         284,313
..     ...    ...         ...             ...
248    홍천군    409         144          67,067
249    화성시   5608         128         961,688
250    화순군    577         217          60,886
251    화천군    148         150          22,965
252    횡성군    211         145          46,238

[253 rows x 4 columns]

In [379]:
df_merge = df_merge.drop(columns=["Unnamed: 0"])

In [380]:
df_merge

    시군구코드명  요양기관수 2024년09월_계_총인구수
0      가평군    526          62,492
1      강남구  12933         558,508
2      강동구   4743         465,090
3      강릉시   1123         208,161
4      강북구   2550         284,313
..     ...    ...             ...
248    홍천군    409          67,067
249    화성시   5608         961,688
250    화순군    577          60,886
251    화천군    148          22,965
252    횡성군    211          46,238

[253 rows x 3 columns]

In [382]:
df_merge['2024년09월_계_총인구수'] = df_merge['2024년09월_계_총인구수'].astype(str).str.replace(',', '', regex=False).astype(int)
df_merge

    시군구코드명  요양기관수  2024년09월_계_총인구수
0      가평군    526            62492
1      강남구  12933           558508
2      강동구   4743           465090
3      강릉시   1123           208161
4      강북구   2550           284313
..     ...    ...              ...
248    홍천군    409            67067
249    화성시   5608           961688
250    화순군    577            60886
251    화천군    148            22965
252    횡성군    211            46238

[253 rows x 3 columns]

In [383]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   시군구코드명           253 non-null    object
 1   요양기관수            253 non-null    int64
 2   2024년09월_계_총인구수  253 non-null    int64
dtypes: int64(2), object(1)
memory usage: 6.1+ KB

In [385]:
df_merge['시군구별인구대비병원비율'] = df_merge['요양기관수'] / df_merge['2024년09월_계_총인구수']

In [386]:
df_merge

    시군구코드명  요양기관수  2024년09월_계_총인구수  시군구별인구대비병원비율
0      가평군    526            62492      0.008417
1      강남구  12933           558508      0.023156
2      강동구   4743           465090      0.010198
3      강릉시   1123           208161      0.005395
4      강북구   2550           284313      0.008969
..     ...    ...              ...           ...
248    홍천군    409            67067      0.006098
249    화성시   5608           961688      0.005831
250    화순군    577            60886      0.009477
251    화천군    148            22965      0.006445
252    횡성군    211            46238      0.004563

[253 rows x 4 columns]

In [387]:
df_merge = df_merge.drop(columns=["요양기관수","2024년09월_계_총인구수"])
df_merge

    시군구코드명  시군구별인구대비병원비율
0      가평군      0.008417
1      강남구      0.023156
2      강동구      0.010198
3      강릉시      0.005395
4      강북구      0.008969
..     ...           ...
248    홍천군      0.006098
249    화성시      0.005831
250    화순군      0.009477
251    화천군      0.006445
252    횡성군      0.004563

[253 rows x 2 columns]

In [388]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별 인구&병원.csv")

In [389]:
df_final = pd.merge(df, df_merge, how="left", on="시군구코드명")

In [394]:
df_final.to_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별 인구&병원.csv")

In [392]:
df_final.rename(columns={'인구대비병원수': '시도별인구대비병원수'}, inplace=True)

In [395]:
df = pd.read_excel("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/1.병원정보서비스 2024.9.xlsx")
df.to_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/test.csv")

In [396]:
import pandas as pd
import numpy as np

In [475]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/2021_2분기 filled_data.csv")

In [476]:
df_merge = df[["시도", "요양기관종별", "합계", "내과", "신경과","신경외과","정신건강의학과","외과","심장혈관흉부외과", "산부인과", "소아청소년과", "응급의학과", "재활의학과"]]

In [477]:
df_merge.rename(columns={"합계":"2021_2_합계","내과":"2021_2_내과", "신경과":"2021_2_신경과","신경외과":"2021_2_신경외과","정신건강의학과":"2021_2_정신건강의학과","외과":"2021_2_외과","심장혈관흉부외과":"2021_2_흉부외과", "산부인과":"2021_2_산부인과", "소아청소년과":"2021_2_소아청소년과", "응급의학과":"2021_2_응급의학과", "재활의학과":"2021_2_재활의학과"})

,시도,요양기관종별,2021_2_합계,2021_2_내과,2021_2_신경과,2021_2_신경외과,2021_2_정신건강의학과,2021_2_외과,2021_2_흉부외과,2021_2_산부인과,2021_2_소아청소년과,2021_2_응급의학과,2021_2_재활의학과
0,서울,계,25004,4741,545,679,1016,1573,304,1563,1307,414,602
1,서울,상급종합병원,6455,1629,242,222,159,560,164,232,360,165,104
2,서울,종합병원,3523,861,133,139,76,247,53,191,159,196,57
3,서울,병원,2019,257,35,164,42,141,5,182,66,10,88
4,서울,요양병원,468,104,49,17,8,36,9,13,11,6,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,세종,요양병원,10,0,0,3,0,3,1,2,1,0,0
174,세종,정신병원,2,0,0,0,2,0,0,0,0,0,0
175,세종,의원,263,43,3,5,12,11,2,16,42,1,3
176,세종,보건지소,3,1,0,0,0,0,0,1,0,0,0
177,세종,한방병원,1,0,0,0,0,0,0,0,0,0,0

In [478]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/2022_2분기 filled_data.csv")
df.head()

,시도,요양기관종별,합계,내과,신경과,정신건강의학과,외과,정형외과,신경외과,심장혈관흉부외과,...,방사선종양학과,병리과,진단검사의학과,결핵과,재활의학과,핵의학과,가정의학과,응급의학과,직업환경의학과,예방의학과
0,서울,계,25802,4848,556,1084,1636,1662,688,299,...,130,336,301,18,627,101,1916,430,99,48
1,서울,상급종합병원,6532,1619,248,154,598,255,211,159,...,87,176,141,0,104,64,149,164,27,21
2,서울,종합병원,3580,881,132,76,268,259,142,53,...,25,70,76,0,58,26,112,206,16,9
3,서울,병원,2001,262,42,11,132,403,172,7,...,1,4,5,3,88,2,80,11,12,2
4,서울,요양병원,450,106,43,9,38,12,14,9,...,2,0,2,0,94,0,72,5,0,1

In [479]:
df = df[["시도","요양기관종별","합계", "내과", "신경과","신경외과","정신건강의학과","외과","심장혈관흉부외과", "산부인과", "소아청소년과", "응급의학과", "재활의학과"]]
df

,시도,요양기관종별,합계,내과,신경과,신경외과,정신건강의학과,외과,심장혈관흉부외과,산부인과,소아청소년과,응급의학과,재활의학과
0,서울,계,25802,4848,556,688,1084,1636,299,1612,1375,430,627
1,서울,상급종합병원,6532,1619,248,211,154,598,159,232,406,164,104
2,서울,종합병원,3580,881,132,142,76,268,53,188,160,206,58
3,서울,병원,2001,262,42,172,11,132,7,182,68,11,88
4,서울,요양병원,450,106,43,14,9,38,9,18,8,5,94
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,세종,요양병원,11,0,0,3,0,3,1,1,2,0,0
174,세종,정신병원,2,0,0,0,2,0,0,0,0,0,0
175,세종,의원,278,50,3,5,14,12,2,14,44,1,4
176,세종,보건지소,2,1,0,0,0,0,0,1,0,0,0
177,세종,한방병원,3,1,0,0,0,0,0,0,0,0,0

In [480]:
df.rename(columns={"합계":"2022_2_합계","내과":"2022_2_내과", "신경과":"2022_2_신경과","신경외과":"2022_2_신경외과","정신건강의학과":"2022_2_정신건강의학과","외과":"2022_2_외과","심장혈관흉부외과":"2022_2_흉부외과", "산부인과":"2022_2_산부인과", "소아청소년과":"2022_2_소아청소년과", "응급의학과":"2022_2_응급의학과", "재활의학과":"2022_2_재활의학과"})

,시도,요양기관종별,2022_2_합계,2022_2_내과,2022_2_신경과,2022_2_신경외과,2022_2_정신건강의학과,2022_2_외과,2022_2_흉부외과,2022_2_산부인과,2022_2_소아청소년과,2022_2_응급의학과,2022_2_재활의학과
0,서울,계,25802,4848,556,688,1084,1636,299,1612,1375,430,627
1,서울,상급종합병원,6532,1619,248,211,154,598,159,232,406,164,104
2,서울,종합병원,3580,881,132,142,76,268,53,188,160,206,58
3,서울,병원,2001,262,42,172,11,132,7,182,68,11,88
4,서울,요양병원,450,106,43,14,9,38,9,18,8,5,94
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,세종,요양병원,11,0,0,3,0,3,1,1,2,0,0
174,세종,정신병원,2,0,0,0,2,0,0,0,0,0,0
175,세종,의원,278,50,3,5,14,12,2,14,44,1,4
176,세종,보건지소,2,1,0,0,0,0,0,1,0,0,0
177,세종,한방병원,3,1,0,0,0,0,0,0,0,0,0

In [481]:
df_merge = pd.merge(df_merge, df, how="left", on=["시도", "요양기관종별"])
df_merge.columns

Index(['시도', '요양기관종별', '합계_x', '내과_x', '신경과_x', '신경외과_x', '정신건강의학과_x', '외과_x',
       '심장혈관흉부외과_x', '산부인과_x', '소아청소년과_x', '응급의학과_x', '재활의학과_x', '합계_y',
       '내과_y', '신경과_y', '신경외과_y', '정신건강의학과_y', '외과_y', '심장혈관흉부외과_y', '산부인과_y',
       '소아청소년과_y', '응급의학과_y', '재활의학과_y'],
      dtype='object')

In [ ]:
df_merge

In [490]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/2024_2분기 filled_data.csv")
df.head()

,시도,요양기관종별,합계,내과,신경과,정신건강의학과,외과,정형외과,신경외과,심장혈관흉부외과,...,방사선종양학과,병리과,진단검사의학과,결핵과,재활의학과,핵의학과,가정의학과,응급의학과,직업환경의학과,예방의학과
0,서울,계,27244,5057,596,1214,1679,1751,714,319,...,127,362,313,18,688,94,2055,490,103,45
1,서울,상급종합병원,6655,1616,246,152,598,254,221,160,...,86,175,143,0,110,59,144,181,26,24
2,서울,종합병원,3715,882,149,74,288,261,137,58,...,26,72,79,0,67,26,120,237,20,11
3,서울,병원,1991,262,49,13,116,398,172,9,...,0,2,5,2,102,0,91,7,16,0
4,서울,요양병원,434,106,34,7,40,12,21,13,...,1,0,1,0,78,0,72,3,1,1

In [491]:
df = df[["시도","요양기관종별","합계", "내과", "신경과","신경외과","정신건강의학과","외과","심장혈관흉부외과", "산부인과", "소아청소년과", "응급의학과", "재활의학과"]]

In [505]:
df_merge = df_merge.rename(columns={"합계":"합계_24_2","내과":"내과_24_2", "신경과":"신경과_24_2","신경외과":"신경외과_24_2","정신건강의학과":"정신건강의학과_24_2","외과":"외과_24_2","심장혈관흉부외과":"흉부외과_24_2", "산부인과":"산부인과_24_2", "소아청소년과":"소아청소년과_24_2", "응급의학과":"응급의학과_24_2", "재활의학과":"재활의학과_24_2"})

In [501]:
df_merge = pd.merge(df_merge, df, how="left", on=["시도", "요양기관종별"])

In [506]:
df_merge.columns

Index(['시도', '요양기관종별', '합계_21_2', '내과_21_2', '신경과_21_2', '신경외과_21_2',
       '정신건강의학과_21_2', '외과_21_2', '심장혈관흉부외과_21_2', '산부인과_21_2', '소아청소년과_21_2',
       '응급의학과_21_2', '재활의학과_21_2', '합계_22_2', '내과_22_2', '신경과_22_2',
       '신경외과_22_2', '정신건강의학과_22_2', '외과_22_2', '심장혈관흉부외과_22_2', '산부인과_22_2',
       '소아청소년과_22_2', '응급의학과_22_2', '재활의학과_22_2', '합계_23_2', '내과_23_2',
       '신경과_23_2', '신경외과_23_2', '정신건강의학과_23_2', '외과_23_2', '심장혈관흉부외과_23_2',
       '산부인과_23_2', '소아청소년과_23_2', '응급의학과_23_2', '재활의학과_23_2', '합계_24_2',
       '내과_24_2', '신경과_24_2', '신경외과_24_2', '정신건강의학과_24_2', '외과_24_2',
       '흉부외과_24_2', '산부인과_24_2', '소아청소년과_24_2', '응급의학과_24_2', '재활의학과_24_2'],
      dtype='object')

In [507]:
df_merge.to_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/21-24 필수의료.csv")

In [488]:
def rename_columns(col_name):
    if col_name.endswith('_x'):
        return col_name.replace('_x', '_21_2')
    elif col_name.endswith('_y'):
        return col_name.replace('_y', '_22_2')
    else:
        return col_name + '_23_2'

# 칼럼명 변경 적용
df_merge.columns = [rename_columns(col) for col in df_merge.columns]

In [499]:
df_merge = df_merge.rename(columns={"시도_23_2": "시도", "요양기관종별_23_2":"요양기관종별"})

In [500]:
df_merge

,시도,요양기관종별,합계_21_2,내과_21_2,신경과_21_2,신경외과_21_2,정신건강의학과_21_2,외과_21_2,심장혈관흉부외과_21_2,산부인과_21_2,...,내과_23_2,신경과_23_2,신경외과_23_2,정신건강의학과_23_2,외과_23_2,심장혈관흉부외과_23_2,산부인과_23_2,소아청소년과_23_2,응급의학과_23_2,재활의학과_23_2
0,서울,계,25004,4741,545,679,1016,1573,304,1563,...,5034,568,676,1146,1656,307,1601,1438,450,659
1,서울,상급종합병원,6455,1629,242,222,159,560,164,232,...,1676,248,212,157,597,154,213,438,174,105
2,서울,종합병원,3523,861,133,139,76,247,53,191,...,896,135,136,77,274,60,192,163,217,62
3,서울,병원,2019,257,35,164,42,141,5,182,...,257,47,162,14,138,10,170,70,9,100
4,서울,요양병원,468,104,49,17,8,36,9,13,...,109,37,14,7,40,8,16,10,4,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,세종,요양병원,10,0,0,3,0,3,1,2,...,0,0,3,0,2,1,0,2,0,0
174,세종,정신병원,2,0,0,0,2,0,0,0,...,0,0,0,2,0,0,0,0,0,0
175,세종,의원,263,43,3,5,12,11,2,16,...,58,3,5,17,14,2,16,45,1,5
176,세종,보건지소,3,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
177,세종,한방병원,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [460]:
df_merge = df_merge.rename(columns={"23_2시도":"시도", "23_2요양기관종별":"요양기관종별"})
df_merge.columns

Index(['시도', '요양기관종별', '합계21_2', '내과21_2', '신경과21_2', '신경외과21_2',
       '정신건강의학과21_2', '외과21_2', '심장혈관흉부외과21_2', '산부인과21_2', '소아청소년과21_2',
       '응급의학과21_2', '재활의학과21_2', '합계22_2', '내과22_2', '신경과22_2', '신경외과22_2',
       '정신건강의학과22_2', '외과22_2', '심장혈관흉부외과22_2', '산부인과22_2', '소아청소년과22_2',
       '응급의학과22_2', '재활의학과22_2', '23_2합계', '23_2내과', '23_2신경과', '23_2신경외과',
       '23_2정신건강의학과', '23_2외과', '23_2심장혈관흉부외과', '23_2산부인과', '23_2소아청소년과',
       '23_2응급의학과', '23_2재활의학과'],
      dtype='object')

In [467]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/2024_2분기 filled_data.csv")

In [464]:
df

,시도,요양기관종별,합계,내과,신경과,신경외과,정신건강의학과,외과,심장혈관흉부외과,산부인과,소아청소년과,응급의학과,재활의학과
0,서울,계,27244,5057,596,714,1214,1679,319,1627,1510,490,688
1,서울,상급종합병원,6655,1616,246,221,152,598,160,218,489,181,110
2,서울,종합병원,3715,882,149,137,74,288,58,189,169,237,67
3,서울,병원,1991,262,49,172,13,116,9,170,58,7,102
4,서울,요양병원,434,106,34,21,7,40,13,18,10,3,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,세종,정신병원,2,0,0,0,2,0,0,0,0,0,0
176,세종,의원,315,62,3,4,17,14,2,19,49,2,5
177,세종,보건소,1,0,0,0,0,0,0,1,0,0,0
178,세종,보건지소,1,0,0,0,0,0,0,0,0,0,0
179,세종,한방병원,1,0,0,0,0,1,0,0,0,0,0

In [469]:
df = df.rename(columns={"합계":"24_2_합계","내과":"24_2_내과", "신경과":"24_2_신경과","신경외과":"24_2_신경외과","정신건강의학과":"24_2_정신건강의학과","외과":"24_2_외과","심장혈관흉부외과":"24_2_흉부외과", "산부인과":"24_2_산부인과", "소아청소년과":"24_2_소아청소년과", "응급의학과":"24_2_응급의학과", "재활의학과":"24_2_재활의학과"})
df.columns

Index(['시도', '요양기관종별', '24_2_합계', '24_2_내과', '24_2_신경과', '24_2_신경외과',
       '24_2_정신건강의학과', '24_2_외과', '24_2_흉부외과', '24_2_산부인과', '24_2_소아청소년과',
       '24_2_응급의학과', '24_2_재활의학과'],
      dtype='object')

In [470]:
df_merge = pd.merge(df_merge, df, how="left", on=["시도", "요양기관종별"])

In [471]:
df_merge

,시도,요양기관종별,합계21_2,내과21_2,신경과21_2,신경외과21_2,정신건강의학과21_2,외과21_2,심장혈관흉부외과21_2,산부인과21_2,...,24_2_내과,24_2_신경과,24_2_신경외과,24_2_정신건강의학과,24_2_외과,24_2_흉부외과,24_2_산부인과,24_2_소아청소년과,24_2_응급의학과,24_2_재활의학과
0,서울,계,25004,4741,545,679,1016,1573,304,1563,...,5057,596,714,1214,1679,319,1627,1510,490,688
1,서울,상급종합병원,6455,1629,242,222,159,560,164,232,...,1616,246,221,152,598,160,218,489,181,110
2,서울,종합병원,3523,861,133,139,76,247,53,191,...,882,149,137,74,288,58,189,169,237,67
3,서울,병원,2019,257,35,164,42,141,5,182,...,262,49,172,13,116,9,170,58,7,102
4,서울,요양병원,468,104,49,17,8,36,9,13,...,106,34,21,7,40,13,18,10,3,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,세종,요양병원,10,0,0,3,0,3,1,2,...,0,0,3,0,3,1,0,2,0,0
174,세종,정신병원,2,0,0,0,2,0,0,0,...,0,0,0,2,0,0,0,0,0,0
175,세종,의원,263,43,3,5,12,11,2,16,...,62,3,4,17,14,2,19,49,2,5
176,세종,보건지소,3,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
177,세종,한방병원,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [472]:
df_merge.columns

Index(['시도', '요양기관종별', '합계21_2', '내과21_2', '신경과21_2', '신경외과21_2',
       '정신건강의학과21_2', '외과21_2', '심장혈관흉부외과21_2', '산부인과21_2', '소아청소년과21_2',
       '응급의학과21_2', '재활의학과21_2', '합계22_2', '내과22_2', '신경과22_2', '신경외과22_2',
       '정신건강의학과22_2', '외과22_2', '심장혈관흉부외과22_2', '산부인과22_2', '소아청소년과22_2',
       '응급의학과22_2', '재활의학과22_2', '23_2합계', '23_2내과', '23_2신경과', '23_2신경외과',
       '23_2정신건강의학과', '23_2외과', '23_2심장혈관흉부외과', '23_2산부인과', '23_2소아청소년과',
       '23_2응급의학과', '23_2재활의학과', '24_2_합계', '24_2_내과', '24_2_신경과', '24_2_신경외과',
       '24_2_정신건강의학과', '24_2_외과', '24_2_흉부외과', '24_2_산부인과', '24_2_소아청소년과',
       '24_2_응급의학과', '24_2_재활의학과'],
      dtype='object')

In [474]:
def rename_columns(col_name):
    if col_name.startswith('24_2'):
        return col_name+'_2_2'

# 칼럼명 변경 적용
df_merge.columns = [rename_columns(col) for col in df_merge.columns]
df_merge.columns

Index([              None,               None,               None,
                     None,               None,               None,
                     None,               None,               None,
                     None,               None,               None,
                     None,               None,               None,
                     None,               None,               None,
                     None,               None,               None,
                     None,               None,               None,
                     None,               None,               None,
                     None,               None,               None,
                     None,               None,               None,
                     None,               None,      '24_2합계_24_2',
            '24_2내과_24_2',     '24_2신경과_24_2',    '24_2신경외과_24_2',
       '24_2정신건강의학과_24_2',      '24_2외과_24_2',    '24_2흉부외과_24_2',
          '24_2산부인과_24_2',  '24_2소아청소년과_24_2',   '24_2응급의학과_24_2',
         '24_2재활의학과_24_2'],
      dtype='object')

In [509]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/전문의수종합.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 31 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시도        714 non-null    object
 1   요양기관종별    714 non-null    object
 2   합계        714 non-null    int64
 3   내과        714 non-null    int64
 4   신경과       714 non-null    int64
 5   정신건강의학과   714 non-null    int64
 6   외과        714 non-null    int64
 7   정형외과      714 non-null    int64
 8   신경외과      714 non-null    int64
 9   심장혈관흉부외과  714 non-null    int64
 10  성형외과      714 non-null    int64
 11  마취통증의학과   714 non-null    int64
 12  산부인과      714 non-null    int64
 13  소아청소년과    714 non-null    int64
 14  안과        714 non-null    int64
 15  이비인후과     714 non-null    int64
 16  피부과       714 non-null    int64
 17  비뇨의학과     714 non-null    int64
 18  영상의학과     714 non-null    int64
 19  방사선종양학과   714 non-null    int64
 20  병리과       714 non-null    int64
 21  진단검사의학과   714 non-null    int64
 22  결핵과       714 non-null    int64
 23  재활의학과     714 non-null    int64
 24  핵의학과      714 non-null    int64
 25  가정의학과     714 non-null    int64
 26  응급의학과     714 non-null    int64
 27  직업환경의학과   714 non-null    int64
 28  예방의학과     714 non-null    int64
 29  연도        714 non-null    int64
 30  총인구수      714 non-null    object
dtypes: int64(28), object(3)
memory usage: 173.0+ KB

In [510]:
df = pd.read_csv("/Users/junwoong/Desktop/멋쟁이 사자처럼/Mid_Project/data/시군구별 인구&병원.csv")
df.head()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,암호화요양기호,요양기관명,종별코드명,설립구분코드명,시도코드명,시군구코드명,...,과목별 전문의수,2024년09월_계_총인구수,총병상수,총의사수_y,총병원수,총인구수,인구대비병상수,인구대비의사수,시도별인구대비병원수,시군구별인구대비병원비율
0,0,0,0,0,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,...,0.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755,0.02003
1,1,1,1,1,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,...,0.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755,0.02003
2,2,2,2,2,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,...,0.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755,0.02003
3,3,3,3,3,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,...,1.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755,0.02003
4,4,4,4,4,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxMTkxIzMxIyQxIy...,뽀빠이연합의원,의원,개인,대구,대구중구,...,0.0,94808,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755,0.02003