In [12]:
# 고령인구 대비 의사 수, 병상 수, 병원 수
# 고령인구 대비 의료 진료 횟수

In [13]:
import pandas as pd

In [14]:
df_2024_oldage = pd.read_excel('202409_고령인구현황_OldAge.xlsx')
df_2024_oldage

,행정구역,2024년09월_전체,2024년09월_남자,2024년09월_여자,2024년09월_65세이상전체,2024년09월_65세이상남자,2024년09월_65세이상여자
0,전국 (1000000000),51248233,25517454,25730779,10110695,4481875,5628820
1,서울특별시 (1100000000),9350995,4515791,4835204,1792548,793889,998659
2,부산광역시 (2600000000),3273473,1593783,1679690,770714,337341,433373
3,대구광역시 (2700000000),2365523,1160812,1204711,484973,209183,275790
4,인천광역시 (2800000000),3016520,1507439,1509081,523522,234392,289130
5,광주광역시 (2900000000),1411357,696711,714646,243432,105334,138098
6,대전광역시 (3000000000),1440456,718109,722347,255245,113543,141702
7,울산광역시 (3100000000),1098728,565067,533661,185059,86013,99046
8,세종특별자치시 (3600000000),389443,193854,195589,44554,20098,24456
9,경기도 (4100000000),13680645,6877300,6803345,2230318,1007117,1223201
10,강원특별자치도 (5100000000),1520410,764551,755859,379708,169613,210095
11,충청북도 (4300000000),1590858,809577,781281,344468,154315,190153
12,충청남도 (4400000000),2135373,1095392,1039981,469632,209040,260592
13,전북특별자치도 (5200000000),1741640,867235,874405,434431,188515,245916
14,전라남도 (4600000000),1791496,903669,887827,482096,207878,274218
15,경상북도 (4700000000),2537955,1283804,1254151,650061,285044,365017
16,경상남도 (4800000000),3232297,1628643,1603654,694633,305624,389009
17,제주특별자치도 (5000000000),671064,335717,335347,125301,54936,70365

In [15]:
len(df_2024_oldage.iloc[1:,:]['행정구역'].sort_values())

17

In [16]:
# 202409_고령인구현황_OldAge 와 지역별_인구대비_병상의사병원수의 행정구역명 차이 발생 > 통일시키기
df_2024_oldage['행정구역'] = ['전국', '서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종', '경기', '강원', '충북', '충남', '전북', '전남', '경북', '경남', '제주']
# df_oldage['행정구역']
df_2024_oldage

# 고령인구와 지역별 간 행의 개수 차이 > 고령인구 내 '전국' 제외 > 행정구역명 순서 통일시키기
df_not_whole = df_2024_oldage.iloc[1:,:]
df_not_whole.sort_values('행정구역')

,행정구역,2024년09월_전체,2024년09월_남자,2024년09월_여자,2024년09월_65세이상전체,2024년09월_65세이상남자,2024년09월_65세이상여자
10,강원,1520410,764551,755859,379708,169613,210095
9,경기,13680645,6877300,6803345,2230318,1007117,1223201
16,경남,3232297,1628643,1603654,694633,305624,389009
15,경북,2537955,1283804,1254151,650061,285044,365017
5,광주,1411357,696711,714646,243432,105334,138098
3,대구,2365523,1160812,1204711,484973,209183,275790
6,대전,1440456,718109,722347,255245,113543,141702
2,부산,3273473,1593783,1679690,770714,337341,433373
1,서울,9350995,4515791,4835204,1792548,793889,998659
8,세종,389443,193854,195589,44554,20098,24456
7,울산,1098728,565067,533661,185059,86013,99046
4,인천,3016520,1507439,1509081,523522,234392,289130
14,전남,1791496,903669,887827,482096,207878,274218
13,전북,1741640,867235,874405,434431,188515,245916
17,제주,671064,335717,335347,125301,54936,70365
12,충남,2135373,1095392,1039981,469632,209040,260592
11,충북,1590858,809577,781281,344468,154315,190153

In [17]:
# 행정구역별 65세이상 그룹화
col_65_or_more = df_not_whole.groupby('행정구역')['2024년09월_65세이상전체'].sum().reset_index()
col_65_or_more

   행정구역  2024년09월_65세이상전체
0    강원            379708
1    경기           2230318
2    경남            694633
3    경북            650061
4    광주            243432
5    대구            484973
6    대전            255245
7    부산            770714
8    서울           1792548
9    세종             44554
10   울산            185059
11   인천            523522
12   전남            482096
13   전북            434431
14   제주            125301
15   충남            469632
16   충북            344468

In [18]:
# 지역별_인구대비_병상의사병원수 불러오기
df_beddochospi = pd.read_csv('지역별_인구대비_병상의사병원수.csv')
len(df_beddochospi['행정구역'])

17

In [19]:
# unname 제거
cols = df_beddochospi.iloc[:,1:]
cols

   행정구역    총병상수   총의사수   총병원수        총인구수   인구대비병상수   인구대비의사수   인구대비병원수
0    강원   21537   3798   1975   1520410.0  0.014165  0.014165  0.001299
1    경기  177901  35236  17631  13680645.0  0.013004  0.013004  0.001289
2    경남   74417   8144   4228   3232297.0  0.023023  0.023023  0.001308
3    경북   51591   5580   3396   2537955.0  0.020328  0.020328  0.001338
4    광주   46496   5297   2328   1411357.0  0.032944  0.032944  0.001649
5    대구   50793   8345   4151   2365523.0  0.021472  0.021472  0.001755
6    대전   28287   4982   2345   1440456.0  0.019638  0.019638  0.001628
7    부산   83801  11545   5571   3273473.0  0.025600  0.025600  0.001702
8    서울  120961  42011  19158   9350995.0  0.012936  0.012936  0.002049
9    세종    3210    801    463    389443.0  0.008243  0.008243  0.001189
10   울산   18650   2741   1426   1098728.0  0.016974  0.016974  0.001298
11   인천   45952   8029   3799   3016520.0  0.015233  0.015233  0.001259
12   전남   52520   4664   2622   1791496.0  0.029316  0.029316  0.001464
13   전북   47998   5294   2942   1741640.0  0.027559  0.027559  0.001689
14   제주    7663   1756   1041    671064.0  0.011419  0.011419  0.001551
15   충남   36320   4969   2851   2135373.0  0.017009  0.017009  0.001335
16   충북   27598   3784   2199   1590858.0  0.017348  0.017348  0.001382

In [20]:
# 고령대비병상수, 고령대비총의사수, 고령대비총병원수
col_65_or_more_table = pd.merge(cols, col_65_or_more ,how = 'left', on = '행정구역')
col_65_or_more_table['고령대비병상수'] = col_65_or_more_table['총병상수'] / col_65_or_more_table['2024년09월_65세이상전체']
col_65_or_more_table['고령대비총의사수'] = col_65_or_more_table['총의사수'] / col_65_or_more_table['2024년09월_65세이상전체']
col_65_or_more_table['고령대비총병원수'] = col_65_or_more_table['총병원수'] / col_65_or_more_table['2024년09월_65세이상전체']
col_65_or_more_table['지역별고령비율'] = col_65_or_more_table['총인구수'] / col_65_or_more_table['2024년09월_65세이상전체']
col_65_or_more_table

,행정구역,총병상수,총의사수,총병원수,총인구수,인구대비병상수,인구대비의사수,인구대비병원수,2024년09월_65세이상전체,고령대비병상수,고령대비총의사수,고령대비총병원수,지역별고령비율
0,강원,21537,3798,1975,1520410.0,0.014165,0.014165,0.001299,379708,0.056720,0.010002,0.005201,4.004156
1,경기,177901,35236,17631,13680645.0,0.013004,0.013004,0.001289,2230318,0.079765,0.015799,0.007905,6.133944
2,경남,74417,8144,4228,3232297.0,0.023023,0.023023,0.001308,694633,0.107131,0.011724,0.006087,4.653244
3,경북,51591,5580,3396,2537955.0,0.020328,0.020328,0.001338,650061,0.079363,0.008584,0.005224,3.904180
4,광주,46496,5297,2328,1411357.0,0.032944,0.032944,0.001649,243432,0.191002,0.021760,0.009563,5.797746
5,대구,50793,8345,4151,2365523.0,0.021472,0.021472,0.001755,484973,0.104734,0.017207,0.008559,4.877639
6,대전,28287,4982,2345,1440456.0,0.019638,0.019638,0.001628,255245,0.110823,0.019519,0.009187,5.643425
7,부산,83801,11545,5571,3273473.0,0.025600,0.025600,0.001702,770714,0.108732,0.014980,0.007228,4.247325
8,서울,120961,42011,19158,9350995.0,0.012936,0.012936,0.002049,1792548,0.067480,0.023436,0.010688,5.216594
9,세종,3210,801,463,389443.0,0.008243,0.008243,0.001189,44554,0.072047,0.017978,0.010392,8.740921
10,울산,18650,2741,1426,1098728.0,0.016974,0.016974,0.001298,185059,0.100779,0.014811,0.007706,5.937177
11,인천,45952,8029,3799,3016520.0,0.015233,0.015233,0.001259,523522,0.087775,0.015337,0.007257,5.761974
12,전남,52520,4664,2622,1791496.0,0.029316,0.029316,0.001464,482096,0.108941,0.009674,0.005439,3.716057
13,전북,47998,5294,2942,1741640.0,0.027559,0.027559,0.001689,434431,0.110485,0.012186,0.006772,4.009014
14,제주,7663,1756,1041,671064.0,0.011419,0.011419,0.001551,125301,0.061157,0.014014,0.008308,5.355616
15,충남,36320,4969,2851,2135373.0,0.017009,0.017009,0.001335,469632,0.077337,0.010581,0.006071,4.546907
16,충북,27598,3784,2199,1590858.0,0.017348,0.017348,0.001382,344468,0.080118,0.010985,0.006384,4.618304

In [21]:
col_65_or_more_table.to_csv('65_or_more.csv', index = False)

In [22]:
excel_list = ['2015_oldage.xlsx','2016_oldage.xlsx','2017_oldage.xlsx', '2018_oldage.xlsx', '2019_oldage.xlsx', '2020_oldage.xlsx', '2021_oldage.xlsx', '2022_oldage.xlsx', '2023_oldage.xlsx']

In [23]:
df_2015_oldage = pd.read_excel(excel_list[0])

In [24]:
df_2016_oldage = pd.read_excel(excel_list[1])

In [25]:
df_2017_oldage = pd.read_excel(excel_list[2])

In [26]:
df_2018_oldage = pd.read_excel(excel_list[3])

In [27]:
df_2019_oldage = pd.read_excel(excel_list[4])

In [28]:
df_2020_oldage = pd.read_excel(excel_list[5])

In [29]:
df_2021_oldage = pd.read_excel(excel_list[6])

In [30]:
df_2022_oldage = pd.read_excel(excel_list[7])

In [41]:
df_2023_oldage = pd.read_excel(excel_list[8])
df_2023_oldage

,행정구역,2023년_계_총인구수,2023년_계_연령구간인구수,2023년_계_65~69세,2023년_계_70~74세,2023년_계_75~79세,2023년_계_80~84세,2023년_계_85~89세,2023년_계_90~94세,2023년_계_95~99세,2023년_계_100세 이상,2023년12월_65세이상전체
0,서울특별시 (1100000000),9386034,1733580,609103,417048,321421,228831,110383,36809,8537,1448,1733580
1,부산광역시 (2600000000),3293362,745199,265186,186754,133653,96815,45091,14126,3142,432,745199
2,대구광역시 (2700000000),2374960,466338,161230,115122,80401,64327,32561,10471,1961,265,466338
3,인천광역시 (2800000000),2997410,497057,189467,113644,84181,61416,32981,12064,2813,491,497057
4,광주광역시 (2900000000),1419237,233878,79590,55796,43332,31943,16242,5616,1152,207,233878
5,대전광역시 (3000000000),1442216,244756,89711,57611,41529,31708,16865,5855,1266,211,244756
6,울산광역시 (3100000000),1103661,175709,72262,44196,27390,19039,9018,3068,657,79,175709
7,세종특별자치시 (3600000000),386525,42560,16311,9916,6562,5160,3074,1222,272,43,42560
8,경기도 (4100000000),13630821,2122718,787673,481771,365332,274613,148416,51409,11652,1852,2122718
9,강원특별자치도 (5100000000),1527807,366555,127532,77731,64145,54515,29620,10117,2505,390,366555
10,충청북도 (4300000000),1593469,332237,117118,73657,54776,47659,27590,9289,1892,256,332237
11,충청남도 (4400000000),2130119,454534,146171,101359,77265,67555,43020,15566,3104,494,454534
12,전라북도 (4500000000),1754757,423128,129798,95537,76268,65548,38583,14010,2910,474,423128
13,전라남도 (4600000000),1804217,470874,137522,103680,86242,78836,44854,15935,3213,592,470874
14,경상북도 (4700000000),2554324,630486,204308,149037,103909,95612,54388,18784,3883,565,630486
15,경상남도 (4800000000),3251158,669646,236857,157263,111794,91038,50899,17867,3485,443,669646
16,제주특별자치도 (5000000000),675252,121156,41170,25867,22014,16662,10162,4221,765,295,121156

In [54]:
per_year_oldage = pd.read_excel('연별_고령인구변화.xlsx')
per_year_oldage

,행정구역,2024년09월_65세이상전체,2023년12월_65세이상전체,2022년12월_65세이상전체,2021년12월_65세이상전체,2020년12월_65세이상전체,2019년12월_65세이상전체,2018년12월_65세이상전체,2017년12월_65세이상전체,2016년12월_65세이상전체,2015년12월_65세이상전체
0,서울,1792548,1733580,1658207,1597447,1561139,1478664,1410297,1359901,1295899,1262436
1,부산,770714,745199,712412,681885,657711,620123,589961,565527,536064,514630
2,대구,484973,466338,435698,417060,400494,379277,362934,347459,328901,316122
3,인천,523522,497057,463850,435431,411483,384548,362675,345024,324255,312905
4,광주,243432,233878,222970,213291,205666,195479,187186,180862,172572,166389
5,대전,255245,244756,232663,221207,210784,198691,188530,180667,171568,165528
6,울산,185059,175709,163812,152961,143367,132565,123919,116633,108768,103205
7,세종,44554,42560,40219,37463,34881,31949,29178,26851,24197,22399
8,경기,2230318,2122718,1992807,1881464,1775315,1651341,1551801,1467835,1374475,1318882
9,강원,379708,366555,349874,333176,319691,302886,289386,279976,266152,261671
10,충청,344468,332237,316939,301516,288148,273425,261763,252434,240690,234813
11,충청,469632,454534,436895,419979,405188,386674,372515,362946,350108,341214
12,전라,434431,423128,410619,397619,386203,370676,358410,351282,341203,333524
13,전라,482096,470874,457481,445198,435880,422548,413132,408451,398916,391837
14,경상,650061,630486,618275,596312,573715,549415,529349,512681,492417,479634
15,경상,694633,669646,638801,608379,580258,548257,523165,504460,480278,464019
16,제주,125301,121156,115768,110645,106154,100397,96207,93117,89189,85893

In [55]:
per_year_oldage['2024년_계_총인구수'] = df_2024_oldage['2024년09월_전체']
per_year_oldage['2023년_계_총인구수'] = df_2023_oldage['2023년_계_총인구수']
per_year_oldage['2022년_계_총인구수'] = df_2022_oldage['2022년_계_총인구수']
per_year_oldage['2021년_계_총인구수'] = df_2021_oldage['2021년_계_총인구수']
per_year_oldage['2020년_계_총인구수'] = df_2020_oldage['2020년_계_총인구수']
per_year_oldage['2019년_계_총인구수'] = df_2019_oldage['2019년_계_총인구수']
per_year_oldage['2018년_계_총인구수'] = df_2018_oldage['2018년_계_총인구수']
per_year_oldage['2017년_계_총인구수'] = df_2017_oldage['2017년_계_총인구수']
per_year_oldage['2016년_계_총인구수'] = df_2016_oldage['2016년_계_총인구수']
per_year_oldage['2015년_계_총인구수'] = df_2015_oldage['2015년_계_총인구수']
per_year_oldage

,행정구역,2024년09월_65세이상전체,2023년12월_65세이상전체,2022년12월_65세이상전체,2021년12월_65세이상전체,2020년12월_65세이상전체,2019년12월_65세이상전체,2018년12월_65세이상전체,2017년12월_65세이상전체,2016년12월_65세이상전체,...,2024년_계_총인구수,2023년_계_총인구수,2022년_계_총인구수,2021년_계_총인구수,2020년_계_총인구수,2019년_계_총인구수,2018년_계_총인구수,2017년_계_총인구수,2016년_계_총인구수,2015년_계_총인구수
0,서울,1792548,1733580,1658207,1597447,1561139,1478664,1410297,1359901,1295899,...,51248233,9386034,9428372,9509458,9668465,9729107,9765623,9857426,9930616,10022181
1,부산,770714,745199,712412,681885,657711,620123,589961,565527,536064,...,9350995,3293362,3317812,3350380,3391946,3413841,3441453,3470653,3498529,3513777
2,대구,484973,466338,435698,417060,400494,379277,362934,347459,328901,...,3273473,2374960,2363691,2385412,2418346,2438031,2461769,2475231,2484557,2487829
3,인천,523522,497057,463850,435431,411483,384548,362675,345024,324255,...,2365523,2997410,2967314,2948375,2942828,2957026,2954642,2948542,2943069,2925815
4,광주,243432,233878,222970,213291,205666,195479,187186,180862,172572,...,3016520,1419237,1431050,1441611,1450062,1456468,1459336,1463770,1469214,1472199
5,대전,255245,244756,232663,221207,210784,198691,188530,180667,171568,...,1411357,1442216,1446072,1452251,1463882,1474870,1489936,1502227,1514370,1518775
6,울산,185059,175709,163812,152961,143367,132565,123919,116633,108768,...,1440456,1103661,1110663,1121592,1136017,1148019,1155623,1165132,1172304,1173534
7,세종,44554,42560,40219,37463,34881,31949,29178,26851,24197,...,1098728,386525,383591,371895,355831,340575,314126,280100,243048,210884
8,경기,2230318,2122718,1992807,1881464,1775315,1651341,1551801,1467835,1374475,...,389443,13630821,13589432,13565450,13427014,13239666,13077153,12873895,12716780,12522606
9,강원,379708,366555,349874,333176,319691,302886,289386,279976,266152,...,13680645,1527807,1536498,1538492,1542840,1541502,1543052,1550142,1550806,1549507
10,충청,344468,332237,316939,301516,288148,273425,261763,252434,240690,...,1520410,1593469,1595058,1597427,1600837,1600007,1599252,1594432,1591625,1583952
11,충청,469632,454534,436895,419979,405188,386674,372515,362946,350108,...,1590858,2130119,2123037,2119257,2121029,2123709,2126282,2116770,2096727,2077649
12,전라,434431,423128,410619,397619,386203,370676,358410,351282,341203,...,2135373,1754757,1769607,1786855,1804104,1818917,1836832,1854607,1864791,1869711
13,전라,482096,470874,457481,445198,435880,422548,413132,408451,398916,...,1741640,1804217,1817697,1832803,1851549,1868745,1882970,1896424,1903914,1908996
14,경상,650061,630486,618275,596312,573715,549415,529349,512681,492417,...,1791496,2554324,2600492,2626609,2639422,2665836,2676831,2691706,2700398,2702826
15,경상,694633,669646,638801,608379,580258,548257,523165,504460,480278,...,2537955,3251158,3280493,3314183,3340216,3362553,3373988,3380404,3373871,3364702
16,제주,125301,121156,115768,110645,106154,100397,96207,93117,89189,...,3232297,675252,678159,676759,674635,670989,667191,657083,641597,624395

In [56]:
per_year_oldage.columns

Index(['행정구역', '2024년09월_65세이상전체', '2023년12월_65세이상전체', '2022년12월_65세이상전체',
       '2021년12월_65세이상전체', '2020년12월_65세이상전체', '2019년12월_65세이상전체',
       '2018년12월_65세이상전체', '2017년12월_65세이상전체', '2016년12월_65세이상전체',
       '2015년12월_65세이상전체', '2024년_계_총인구수', '2023년_계_총인구수', '2022년_계_총인구수',
       '2021년_계_총인구수', '2020년_계_총인구수', '2019년_계_총인구수', '2018년_계_총인구수',
       '2017년_계_총인구수', '2016년_계_총인구수', '2015년_계_총인구수'],
      dtype='object')

In [57]:
# 수도권 고령화
mask1= per_year_oldage['행정구역'].isin(['서울', '경기', '인천'])
mask1

capital_region = per_year_oldage.loc[mask1,:].reset_index()
capital_region = capital_region.iloc[:,1:]
capital_region

,행정구역,2024년09월_65세이상전체,2023년12월_65세이상전체,2022년12월_65세이상전체,2021년12월_65세이상전체,2020년12월_65세이상전체,2019년12월_65세이상전체,2018년12월_65세이상전체,2017년12월_65세이상전체,2016년12월_65세이상전체,...,2024년_계_총인구수,2023년_계_총인구수,2022년_계_총인구수,2021년_계_총인구수,2020년_계_총인구수,2019년_계_총인구수,2018년_계_총인구수,2017년_계_총인구수,2016년_계_총인구수,2015년_계_총인구수
0,서울,1792548,1733580,1658207,1597447,1561139,1478664,1410297,1359901,1295899,...,51248233,9386034,9428372,9509458,9668465,9729107,9765623,9857426,9930616,10022181
1,인천,523522,497057,463850,435431,411483,384548,362675,345024,324255,...,2365523,2997410,2967314,2948375,2942828,2957026,2954642,2948542,2943069,2925815
2,경기,2230318,2122718,1992807,1881464,1775315,1651341,1551801,1467835,1374475,...,389443,13630821,13589432,13565450,13427014,13239666,13077153,12873895,12716780,12522606

In [61]:
capital_region.to_csv('수도권고령화.csv', index = False)

In [58]:
# 비수도권 고령화
mask2 = ~per_year_oldage['행정구역'].isin(['서울', '경기', '인천'])
mask2
noncapital_region = per_year_oldage.loc[mask2,:].reset_index()
noncapital_region = noncapital_region.iloc[:,1:]
noncapital_region

,행정구역,2024년09월_65세이상전체,2023년12월_65세이상전체,2022년12월_65세이상전체,2021년12월_65세이상전체,2020년12월_65세이상전체,2019년12월_65세이상전체,2018년12월_65세이상전체,2017년12월_65세이상전체,2016년12월_65세이상전체,...,2024년_계_총인구수,2023년_계_총인구수,2022년_계_총인구수,2021년_계_총인구수,2020년_계_총인구수,2019년_계_총인구수,2018년_계_총인구수,2017년_계_총인구수,2016년_계_총인구수,2015년_계_총인구수
0,부산,770714,745199,712412,681885,657711,620123,589961,565527,536064,...,9350995,3293362,3317812,3350380,3391946,3413841,3441453,3470653,3498529,3513777
1,대구,484973,466338,435698,417060,400494,379277,362934,347459,328901,...,3273473,2374960,2363691,2385412,2418346,2438031,2461769,2475231,2484557,2487829
2,광주,243432,233878,222970,213291,205666,195479,187186,180862,172572,...,3016520,1419237,1431050,1441611,1450062,1456468,1459336,1463770,1469214,1472199
3,대전,255245,244756,232663,221207,210784,198691,188530,180667,171568,...,1411357,1442216,1446072,1452251,1463882,1474870,1489936,1502227,1514370,1518775
4,울산,185059,175709,163812,152961,143367,132565,123919,116633,108768,...,1440456,1103661,1110663,1121592,1136017,1148019,1155623,1165132,1172304,1173534
5,세종,44554,42560,40219,37463,34881,31949,29178,26851,24197,...,1098728,386525,383591,371895,355831,340575,314126,280100,243048,210884
6,강원,379708,366555,349874,333176,319691,302886,289386,279976,266152,...,13680645,1527807,1536498,1538492,1542840,1541502,1543052,1550142,1550806,1549507
7,충청,344468,332237,316939,301516,288148,273425,261763,252434,240690,...,1520410,1593469,1595058,1597427,1600837,1600007,1599252,1594432,1591625,1583952
8,충청,469632,454534,436895,419979,405188,386674,372515,362946,350108,...,1590858,2130119,2123037,2119257,2121029,2123709,2126282,2116770,2096727,2077649
9,전라,434431,423128,410619,397619,386203,370676,358410,351282,341203,...,2135373,1754757,1769607,1786855,1804104,1818917,1836832,1854607,1864791,1869711
10,전라,482096,470874,457481,445198,435880,422548,413132,408451,398916,...,1741640,1804217,1817697,1832803,1851549,1868745,1882970,1896424,1903914,1908996
11,경상,650061,630486,618275,596312,573715,549415,529349,512681,492417,...,1791496,2554324,2600492,2626609,2639422,2665836,2676831,2691706,2700398,2702826
12,경상,694633,669646,638801,608379,580258,548257,523165,504460,480278,...,2537955,3251158,3280493,3314183,3340216,3362553,3373988,3380404,3373871,3364702
13,제주,125301,121156,115768,110645,106154,100397,96207,93117,89189,...,3232297,675252,678159,676759,674635,670989,667191,657083,641597,624395

In [62]:
noncapital_region.to_csv('비수도권고령화.csv', index = False)

In [59]:
# 수도권 & 비수도권(15~24) 고령화 인구
capi_gap = pd.concat([capital_region, noncapital_region], axis = 0, ignore_index=True)
capi_gap

,행정구역,2024년09월_65세이상전체,2023년12월_65세이상전체,2022년12월_65세이상전체,2021년12월_65세이상전체,2020년12월_65세이상전체,2019년12월_65세이상전체,2018년12월_65세이상전체,2017년12월_65세이상전체,2016년12월_65세이상전체,...,2024년_계_총인구수,2023년_계_총인구수,2022년_계_총인구수,2021년_계_총인구수,2020년_계_총인구수,2019년_계_총인구수,2018년_계_총인구수,2017년_계_총인구수,2016년_계_총인구수,2015년_계_총인구수
0,서울,1792548,1733580,1658207,1597447,1561139,1478664,1410297,1359901,1295899,...,51248233,9386034,9428372,9509458,9668465,9729107,9765623,9857426,9930616,10022181
1,인천,523522,497057,463850,435431,411483,384548,362675,345024,324255,...,2365523,2997410,2967314,2948375,2942828,2957026,2954642,2948542,2943069,2925815
2,경기,2230318,2122718,1992807,1881464,1775315,1651341,1551801,1467835,1374475,...,389443,13630821,13589432,13565450,13427014,13239666,13077153,12873895,12716780,12522606
3,부산,770714,745199,712412,681885,657711,620123,589961,565527,536064,...,9350995,3293362,3317812,3350380,3391946,3413841,3441453,3470653,3498529,3513777
4,대구,484973,466338,435698,417060,400494,379277,362934,347459,328901,...,3273473,2374960,2363691,2385412,2418346,2438031,2461769,2475231,2484557,2487829
5,광주,243432,233878,222970,213291,205666,195479,187186,180862,172572,...,3016520,1419237,1431050,1441611,1450062,1456468,1459336,1463770,1469214,1472199
6,대전,255245,244756,232663,221207,210784,198691,188530,180667,171568,...,1411357,1442216,1446072,1452251,1463882,1474870,1489936,1502227,1514370,1518775
7,울산,185059,175709,163812,152961,143367,132565,123919,116633,108768,...,1440456,1103661,1110663,1121592,1136017,1148019,1155623,1165132,1172304,1173534
8,세종,44554,42560,40219,37463,34881,31949,29178,26851,24197,...,1098728,386525,383591,371895,355831,340575,314126,280100,243048,210884
9,강원,379708,366555,349874,333176,319691,302886,289386,279976,266152,...,13680645,1527807,1536498,1538492,1542840,1541502,1543052,1550142,1550806,1549507
10,충청,344468,332237,316939,301516,288148,273425,261763,252434,240690,...,1520410,1593469,1595058,1597427,1600837,1600007,1599252,1594432,1591625,1583952
11,충청,469632,454534,436895,419979,405188,386674,372515,362946,350108,...,1590858,2130119,2123037,2119257,2121029,2123709,2126282,2116770,2096727,2077649
12,전라,434431,423128,410619,397619,386203,370676,358410,351282,341203,...,2135373,1754757,1769607,1786855,1804104,1818917,1836832,1854607,1864791,1869711
13,전라,482096,470874,457481,445198,435880,422548,413132,408451,398916,...,1741640,1804217,1817697,1832803,1851549,1868745,1882970,1896424,1903914,1908996
14,경상,650061,630486,618275,596312,573715,549415,529349,512681,492417,...,1791496,2554324,2600492,2626609,2639422,2665836,2676831,2691706,2700398,2702826
15,경상,694633,669646,638801,608379,580258,548257,523165,504460,480278,...,2537955,3251158,3280493,3314183,3340216,3362553,3373988,3380404,3373871,3364702
16,제주,125301,121156,115768,110645,106154,100397,96207,93117,89189,...,3232297,675252,678159,676759,674635,670989,667191,657083,641597,624395

In [63]:
capi_gap.to_csv('수도권 & 비수도권(15~24) 고령화 인구.csv', index = False)

In [60]:
capi_gap.isnull().sum()

행정구역                0
2024년09월_65세이상전체    0
2023년12월_65세이상전체    0
2022년12월_65세이상전체    0
2021년12월_65세이상전체    0
2020년12월_65세이상전체    0
2019년12월_65세이상전체    0
2018년12월_65세이상전체    0
2017년12월_65세이상전체    0
2016년12월_65세이상전체    0
2015년12월_65세이상전체    0
2024년_계_총인구수        0
2023년_계_총인구수        0
2022년_계_총인구수        0
2021년_계_총인구수        0
2020년_계_총인구수        0
2019년_계_총인구수        0
2018년_계_총인구수        0
2017년_계_총인구수        0
2016년_계_총인구수        0
2015년_계_총인구수        0
dtype: int64